export const DOORKEY_BAKER_STREET_12_STAIRS_GF = "DOORKEY_BAKER_STREET_12_STAIRS_GF";
export const DOORKEY_BAKER_STREET_12_APT_F1 = "DOORKEY_BAKER_STREET_12_APT_F1";
export const DOORKEY_BAKER_STREET_12_STAIRS_F1 = "DOORKEY_BAKER_STREET_12_STAIRS_F1";
export const DOORKEY_BAKER_STREET_12_APT_F2 = "DOORKEY_BAKER_STREET_12_APT_F2";
export const DOORKEY_BAKER_STREET_12_STAIRS_F2 = "DOORKEY_BAKER_STREET_12_STAIRS_F2";
export const DOORKEY_BAKER_STREET_12_APT_F3 = "DOORKEY_BAKER_STREET_12_APT_F3";
export const DOORKEY_BAKER_STREET_12_STAIRS_F3 = "DOORKEY_BAKER_STREET_12_STAIRS_F3";
export const DOORKEY_BAKER_STREET_12_APT_F4 = "DOORKEY_BAKER_STREET_12_APT_F4";