export const DOORKEY_NEWTOWN_APPARTMENTS_FRONT_DOOR = "DOORKEY_C2_1";
export const DOORKEY_NEWTOWN_APPARTMENTS_APP_1_DOOR = "DOORKEY_C2_2";
export const DOORKEY_NEWTOWN_APPARTMENTS_APP_2_DOOR = "DOORKEY_C2_3";
export const DOORKEY_NEWTOWN_APPARTMENTS_APP_3_DOOR = "DOORKEY_C2_4";
export const DOORKEY_NEWTOWN_APPARTMENTS_APP_4_DOOR = "DOORKEY_C2_5";
export const DOORKEY_NEWTOWN_APPARTMENTS_APP_5_DOOR = "DOORKEY_C2_6";