import GBGFLobby from './Grey-Building/GF/GB-GF-lobby';
import GBGFHallLeft from './Grey-Building/GF/GB-GF-hall-left';
import GBGFHallRight from './Grey-Building/GF/GB-GF-hall-right';
import { MAP_LH_GB_GF_APT1, MAP_LH_GB_GF_APT1_BED, MAP_LH_GB_GF_APT1_TOILET } from './Grey-Building/GF/GB-GF-apt1';
import { MAP_LH_GB_GF_APT2, MAP_LH_GB_GF_APT2_BED, MAP_LH_GB_GF_APT2_TOILET } from './Grey-Building/GF/GB-GF-apt2';
import { MAP_LH_GB_GF_APT3, MAP_LH_GB_GF_APT3_BED, MAP_LH_GB_GF_APT3_TOILET } from './Grey-Building/GF/GB-GF-apt3';
import { MAP_LH_GB_GF_APT4, MAP_LH_GB_GF_APT4_BED, MAP_LH_GB_GF_APT4_TOILET } from './Grey-Building/GF/GB-GF-apt4';
import { MAP_LH_GB_GF_APT5, MAP_LH_GB_GF_APT5_BED, MAP_LH_GB_GF_APT5_TOILET } from './Grey-Building/GF/GB-GF-apt5';
import { MAP_LH_GB_GF_APT6, MAP_LH_GB_GF_APT6_BED, MAP_LH_GB_GF_APT6_TOILET } from './Grey-Building/GF/GB-GF-apt6';
import GBF1Lobby from './Grey-Building/F1/GB-F1-lobby';
import GBF1HallLeft from './Grey-Building/F1/GB-F1-hall-left';
import GBF1HallRight from './Grey-Building/F1/GB-F1-hall-right';
import { MAP_LH_GB_F1_APT1, MAP_LH_GB_F1_APT1_BED, MAP_LH_GB_F1_APT1_TOILET } from './Grey-Building/F1/GB-F1-apt1';
import { MAP_LH_GB_F1_APT2, MAP_LH_GB_F1_APT2_BED, MAP_LH_GB_F1_APT2_TOILET } from './Grey-Building/F1/GB-F1-apt2';
import { MAP_LH_GB_F1_APT3, MAP_LH_GB_F1_APT3_BED, MAP_LH_GB_F1_APT3_TOILET } from './Grey-Building/F1/GB-F1-apt3';
import { MAP_LH_GB_F1_APT4, MAP_LH_GB_F1_APT4_BED, MAP_LH_GB_F1_APT4_TOILET } from './Grey-Building/F1/GB-F1-apt4';
import { MAP_LH_GB_F1_APT5, MAP_LH_GB_F1_APT5_BED, MAP_LH_GB_F1_APT5_TOILET } from './Grey-Building/F1/GB-F1-apt5';
import { MAP_LH_GB_F1_APT6, MAP_LH_GB_F1_APT6_BED, MAP_LH_GB_F1_APT6_TOILET } from './Grey-Building/F1/GB-F1-apt6';
import GBF2Lobby from './Grey-Building/F2/GB-F2-lobby';
import GBF2HallLeft from './Grey-Building/F2/GB-F2-hall-left';
import { MAP_LH_GB_F2_APT1, MAP_LH_GB_F2_APT1_BED, MAP_LH_GB_F2_APT1_TOILET } from './Grey-Building/F2/GB-F2-apt1';
import { MAP_LH_GB_F2_APT2, MAP_LH_GB_F2_APT2_BED, MAP_LH_GB_F2_APT2_TOILET } from './Grey-Building/F2/GB-F2-apt2';
import { MAP_LH_GB_F2_APT3, MAP_LH_GB_F2_APT3_BED, MAP_LH_GB_F2_APT3_TOILET } from './Grey-Building/F2/GB-F2-apt3';
import GBF3Lobby from './Grey-Building/F3/GB-F3-lobby';
import GBF3HallLeft from './Grey-Building/F3/GB-F3-hall-left';
import GBF3HallRight from './Grey-Building/F3/GB-F3-hall-right';
import { MAP_LH_GB_F3_APT1, MAP_LH_GB_F3_APT1_BED, MAP_LH_GB_F3_APT1_TOILET } from './Grey-Building/F3/GB-F3-apt1';
import { MAP_LH_GB_F3_APT2, MAP_LH_GB_F3_APT2_BED, MAP_LH_GB_F3_APT2_TOILET } from './Grey-Building/F3/GB-F3-apt2';
import { MAP_LH_GB_F3_APT3, MAP_LH_GB_F3_APT3_BED, MAP_LH_GB_F3_APT3_TOILET } from './Grey-Building/F3/GB-F3-apt3';
import { MAP_LH_GB_F3_APT4, MAP_LH_GB_F3_APT4_BED, MAP_LH_GB_F3_APT4_TOILET } from './Grey-Building/F3/GB-F3-apt4';
import { MAP_LH_GB_F3_APT5, MAP_LH_GB_F3_APT5_BED, MAP_LH_GB_F3_APT5_TOILET } from './Grey-Building/F3/GB-F3-apt5';
import { MAP_LH_GB_F3_APT6, MAP_LH_GB_F3_APT6_BED, MAP_LH_GB_F3_APT6_TOILET } from './Grey-Building/F3/GB-F3-apt6';
import GBF4Lobby from './Grey-Building/F4/GB-F4-lobby';
import { MAP_IDS } from '../../mapIds';

export default {
    // Grey Building
    // GF
        [MAP_IDS.LEONARD_HEIGHTS.GREY_BUILDING_GF_LOBBY]: GBGFLobby,
        [MAP_IDS.LEONARD_HEIGHTS.GREY_BUILDING_GF_HALL_LEFT]: GBGFHallLeft,
        [MAP_IDS.LEONARD_HEIGHTS.GREY_BUILDING_GF_HALL_RIGHT]: GBGFHallRight,
        [MAP_IDS.LEONARD_HEIGHTS.GREY_BUILDING_GF_APT1]: MAP_LH_GB_GF_APT1,
        [MAP_IDS.LEONARD_HEIGHTS.GREY_BUILDING_GF_APT1_BEDROOM]: MAP_LH_GB_GF_APT1_BED,
        [MAP_IDS.LEONARD_HEIGHTS.GREY_BUILDING_GF_APT1_TOILET]: MAP_LH_GB_GF_APT1_TOILET,
        [MAP_IDS.LEONARD_HEIGHTS.GREY_BUILDING_GF_APT2]: MAP_LH_GB_GF_APT2,
        [MAP_IDS.LEONARD_HEIGHTS.GREY_BUILDING_GF_APT2_BEDROOM]: MAP_LH_GB_GF_APT2_BED,
        [MAP_IDS.LEONARD_HEIGHTS.GREY_BUILDING_GF_APT2_TOILET]: MAP_LH_GB_GF_APT2_TOILET,
        [MAP_IDS.LEONARD_HEIGHTS.GREY_BUILDING_GF_APT3]: MAP_LH_GB_GF_APT3,
        [MAP_IDS.LEONARD_HEIGHTS.GREY_BUILDING_GF_APT3_BEDROOM]: MAP_LH_GB_GF_APT3_BED,
        [MAP_IDS.LEONARD_HEIGHTS.GREY_BUILDING_GF_APT3_TOILET]: MAP_LH_GB_GF_APT3_TOILET,
        [MAP_IDS.LEONARD_HEIGHTS.GREY_BUILDING_GF_APT4]: MAP_LH_GB_GF_APT4,
        [MAP_IDS.LEONARD_HEIGHTS.GREY_BUILDING_GF_APT4_BEDROOM]: MAP_LH_GB_GF_APT4_BED,
        [MAP_IDS.LEONARD_HEIGHTS.GREY_BUILDING_GF_APT4_TOILET]: MAP_LH_GB_GF_APT4_TOILET,
        [MAP_IDS.LEONARD_HEIGHTS.GREY_BUILDING_GF_APT5]: MAP_LH_GB_GF_APT5,
        [MAP_IDS.LEONARD_HEIGHTS.GREY_BUILDING_GF_APT5_BEDROOM]: MAP_LH_GB_GF_APT5_BED,
        [MAP_IDS.LEONARD_HEIGHTS.GREY_BUILDING_GF_APT5_TOILET]: MAP_LH_GB_GF_APT5_TOILET,
        [MAP_IDS.LEONARD_HEIGHTS.GREY_BUILDING_GF_APT6]: MAP_LH_GB_GF_APT6,
        [MAP_IDS.LEONARD_HEIGHTS.GREY_BUILDING_GF_APT6_BEDROOM]: MAP_LH_GB_GF_APT6_BED,
        [MAP_IDS.LEONARD_HEIGHTS.GREY_BUILDING_GF_APT6_TOILET]: MAP_LH_GB_GF_APT6_TOILET,
    //
    // F1
        [MAP_IDS.LEONARD_HEIGHTS.GREY_BUILDING_F1_LOBBY]: GBF1Lobby,
        [MAP_IDS.LEONARD_HEIGHTS.GREY_BUILDING_F1_HALL_LEFT]: GBF1HallLeft,
        [MAP_IDS.LEONARD_HEIGHTS.GREY_BUILDING_F1_HALL_RIGHT]: GBF1HallRight,
        [MAP_IDS.LEONARD_HEIGHTS.GREY_BUILDING_F1_APT1]: MAP_LH_GB_F1_APT1,
        [MAP_IDS.LEONARD_HEIGHTS.GREY_BUILDING_F1_APT1_BEDROOM]: MAP_LH_GB_F1_APT1_BED,
        [MAP_IDS.LEONARD_HEIGHTS.GREY_BUILDING_F1_APT1_TOILET]: MAP_LH_GB_F1_APT1_TOILET,
        [MAP_IDS.LEONARD_HEIGHTS.GREY_BUILDING_F1_APT2]: MAP_LH_GB_F1_APT2,
        [MAP_IDS.LEONARD_HEIGHTS.GREY_BUILDING_F1_APT2_BEDROOM]: MAP_LH_GB_F1_APT2_BED,
        [MAP_IDS.LEONARD_HEIGHTS.GREY_BUILDING_F1_APT2_TOILET]: MAP_LH_GB_F1_APT2_TOILET,
        [MAP_IDS.LEONARD_HEIGHTS.GREY_BUILDING_F1_APT3]: MAP_LH_GB_F1_APT3,
        [MAP_IDS.LEONARD_HEIGHTS.GREY_BUILDING_F1_APT3_BEDROOM]: MAP_LH_GB_F1_APT3_BED,
        [MAP_IDS.LEONARD_HEIGHTS.GREY_BUILDING_F1_APT3_TOILET]: MAP_LH_GB_F1_APT3_TOILET,
        [MAP_IDS.LEONARD_HEIGHTS.GREY_BUILDING_F1_APT4]: MAP_LH_GB_F1_APT4,
        [MAP_IDS.LEONARD_HEIGHTS.GREY_BUILDING_F1_APT4_BEDROOM]: MAP_LH_GB_F1_APT4_BED,
        [MAP_IDS.LEONARD_HEIGHTS.GREY_BUILDING_F1_APT4_TOILET]: MAP_LH_GB_F1_APT4_TOILET,
        [MAP_IDS.LEONARD_HEIGHTS.GREY_BUILDING_F1_APT5]: MAP_LH_GB_F1_APT5,
        [MAP_IDS.LEONARD_HEIGHTS.GREY_BUILDING_F1_APT5_BEDROOM]: MAP_LH_GB_F1_APT5_BED,
        [MAP_IDS.LEONARD_HEIGHTS.GREY_BUILDING_F1_APT5_TOILET]: MAP_LH_GB_F1_APT5_TOILET,
        [MAP_IDS.LEONARD_HEIGHTS.GREY_BUILDING_F1_APT6]: MAP_LH_GB_F1_APT6,
        [MAP_IDS.LEONARD_HEIGHTS.GREY_BUILDING_F1_APT6_BEDROOM]: MAP_LH_GB_F1_APT6_BED,
        [MAP_IDS.LEONARD_HEIGHTS.GREY_BUILDING_F1_APT6_TOILET]: MAP_LH_GB_F1_APT6_TOILET,
    //
    // F2
        [MAP_IDS.LEONARD_HEIGHTS.GREY_BUILDING_F2_LOBBY]: GBF2Lobby,
        [MAP_IDS.LEONARD_HEIGHTS.GREY_BUILDING_F2_HALL_LEFT]: GBF2HallLeft,
        [MAP_IDS.LEONARD_HEIGHTS.GREY_BUILDING_F2_APT1]: MAP_LH_GB_F2_APT1,
        [MAP_IDS.LEONARD_HEIGHTS.GREY_BUILDING_F2_APT1_BEDROOM]: MAP_LH_GB_F2_APT1_BED,
        [MAP_IDS.LEONARD_HEIGHTS.GREY_BUILDING_F2_APT1_TOILET]: MAP_LH_GB_F2_APT1_TOILET,
        [MAP_IDS.LEONARD_HEIGHTS.GREY_BUILDING_F2_APT2]: MAP_LH_GB_F2_APT2,
        [MAP_IDS.LEONARD_HEIGHTS.GREY_BUILDING_F2_APT2_BEDROOM]: MAP_LH_GB_F2_APT2_BED,
        [MAP_IDS.LEONARD_HEIGHTS.GREY_BUILDING_F2_APT2_TOILET]: MAP_LH_GB_F2_APT2_TOILET,
        [MAP_IDS.LEONARD_HEIGHTS.GREY_BUILDING_F2_APT3]: MAP_LH_GB_F2_APT3,
        [MAP_IDS.LEONARD_HEIGHTS.GREY_BUILDING_F2_APT3_BEDROOM]: MAP_LH_GB_F2_APT3_BED,
        [MAP_IDS.LEONARD_HEIGHTS.GREY_BUILDING_F2_APT3_TOILET]: MAP_LH_GB_F2_APT3_TOILET,
    //
    // F3
        [MAP_IDS.LEONARD_HEIGHTS.GREY_BUILDING_F3_LOBBY]: GBF3Lobby,
        [MAP_IDS.LEONARD_HEIGHTS.GREY_BUILDING_F3_HALL_LEFT]: GBF3HallLeft,
        [MAP_IDS.LEONARD_HEIGHTS.GREY_BUILDING_F3_HALL_RIGHT]: GBF3HallRight,
        [MAP_IDS.LEONARD_HEIGHTS.GREY_BUILDING_F3_APT1]: MAP_LH_GB_F3_APT1,
        [MAP_IDS.LEONARD_HEIGHTS.GREY_BUILDING_F3_APT1_BEDROOM]: MAP_LH_GB_F3_APT1_BED,
        [MAP_IDS.LEONARD_HEIGHTS.GREY_BUILDING_F3_APT1_TOILET]: MAP_LH_GB_F3_APT1_TOILET,
        [MAP_IDS.LEONARD_HEIGHTS.GREY_BUILDING_F3_APT2]: MAP_LH_GB_F3_APT2,
        [MAP_IDS.LEONARD_HEIGHTS.GREY_BUILDING_F3_APT2_BEDROOM]: MAP_LH_GB_F3_APT2_BED,
        [MAP_IDS.LEONARD_HEIGHTS.GREY_BUILDING_F3_APT2_TOILET]: MAP_LH_GB_F3_APT2_TOILET,
        [MAP_IDS.LEONARD_HEIGHTS.GREY_BUILDING_F3_APT3]: MAP_LH_GB_F3_APT3,
        [MAP_IDS.LEONARD_HEIGHTS.GREY_BUILDING_F3_APT3_BEDROOM]: MAP_LH_GB_F3_APT3_BED,
        [MAP_IDS.LEONARD_HEIGHTS.GREY_BUILDING_F3_APT3_TOILET]: MAP_LH_GB_F3_APT3_TOILET,
        [MAP_IDS.LEONARD_HEIGHTS.GREY_BUILDING_F3_APT4]: MAP_LH_GB_F3_APT4,
        [MAP_IDS.LEONARD_HEIGHTS.GREY_BUILDING_F3_APT4_BEDROOM]: MAP_LH_GB_F3_APT4_BED,
        [MAP_IDS.LEONARD_HEIGHTS.GREY_BUILDING_F3_APT4_TOILET]: MAP_LH_GB_F3_APT4_TOILET,
        [MAP_IDS.LEONARD_HEIGHTS.GREY_BUILDING_F3_APT5]: MAP_LH_GB_F3_APT5,
        [MAP_IDS.LEONARD_HEIGHTS.GREY_BUILDING_F3_APT5_BEDROOM]: MAP_LH_GB_F3_APT5_BED,
        [MAP_IDS.LEONARD_HEIGHTS.GREY_BUILDING_F3_APT5_TOILET]: MAP_LH_GB_F3_APT5_TOILET,
        [MAP_IDS.LEONARD_HEIGHTS.GREY_BUILDING_F3_APT6]: MAP_LH_GB_F3_APT6,
        [MAP_IDS.LEONARD_HEIGHTS.GREY_BUILDING_F3_APT6_BEDROOM]: MAP_LH_GB_F3_APT6_BED,
        [MAP_IDS.LEONARD_HEIGHTS.GREY_BUILDING_F3_APT6_TOILET]: MAP_LH_GB_F3_APT6_TOILET,
    //
    // F4
        [MAP_IDS.LEONARD_HEIGHTS.GREY_BUILDING_F4_LOBBY]: GBF4Lobby
    //
}