export const DOORKEY_GREY_BUILDING_GF_LEFT_HALL = "DOORKEY_GREY_BUILDING_GF_LOBBY_LEFT_HALL";
export const DOORKEY_GREY_BUILDING_GF_RIGHT_HALL = "DOORKEY_GREY_BUILDING_GF_LOBBY_RIGHT_HALL";

export const DOORKEY_GREY_BUILDING_GF_APT1 = "DOORKEY_GREY_BUILDING_GF_APT1";
export const DOORKEY_GREY_BUILDING_GF_APT2 = "DOORKEY_GREY_BUILDING_GF_APT2";
export const DOORKEY_GREY_BUILDING_GF_APT3 = "DOORKEY_GREY_BUILDING_GF_APT3";
export const DOORKEY_GREY_BUILDING_GF_APT4 = "DOORKEY_GREY_BUILDING_GF_APT4";
export const DOORKEY_GREY_BUILDING_GF_APT5 = "DOORKEY_GREY_BUILDING_GF_APT5";
export const DOORKEY_GREY_BUILDING_GF_APT6 = "DOORKEY_GREY_BUILDING_GF_APT6";

export const DOORKEY_GREY_BUILDING_GF_APT1_TOILET = "DOORKEY_GREY_BUILDING_GF_APT1_TOILET";
export const DOORKEY_GREY_BUILDING_GF_APT1_BEDROOM = "DOORKEY_GREY_BUILDING_GF_APT1_BEDROOM";

export const DOORKEY_GREY_BUILDING_GF_APT2_TOILET = "DOORKEY_GREY_BUILDING_GF_APT2_TOILET";
export const DOORKEY_GREY_BUILDING_GF_APT2_BEDROOM = "DOORKEY_GREY_BUILDING_GF_APT2_BEDROOM";

export const DOORKEY_GREY_BUILDING_GF_APT3_TOILET = "DOORKEY_GREY_BUILDING_GF_APT3_TOILET";
export const DOORKEY_GREY_BUILDING_GF_APT3_BEDROOM = "DOORKEY_GREY_BUILDING_GF_APT3_BEDROOM";

export const DOORKEY_GREY_BUILDING_GF_APT4_TOILET = "DOORKEY_GREY_BUILDING_GF_APT4_TOILET";
export const DOORKEY_GREY_BUILDING_GF_APT4_BEDROOM = "DOORKEY_GREY_BUILDING_GF_APT4_BEDROOM";

export const DOORKEY_GREY_BUILDING_GF_APT5_TOILET = "DOORKEY_GREY_BUILDING_GF_APT5_TOILET";
export const DOORKEY_GREY_BUILDING_GF_APT5_BEDROOM = "DOORKEY_GREY_BUILDING_GF_APT5_BEDROOM";

export const DOORKEY_GREY_BUILDING_GF_APT6_TOILET = "DOORKEY_GREY_BUILDING_GF_APT6_TOILET";
export const DOORKEY_GREY_BUILDING_GF_APT6_BEDROOM = "DOORKEY_GREY_BUILDING_GF_APT6_BEDROOM";