import { NEIGHBOURHOOD_IDS } from "./neighbourhoodIds";

type MapIds = {
    LEONARD_HEIGHTS: LeonardHeightsMapIds;
    MASTER_ROOMS: MasterRoomsMapIds;
    CINEMATIC_MAPS: CinematicMapsMapIds;
}

type NeighbourhoodMapIds = {
    NEIGHBOURHOOD_KEY: string;
}

type LeonardHeightsMapIds = NeighbourhoodMapIds & {
    HOTEL_THE_TWO_TOWERS_LOBBY: string;

    CLUB_SHELTER_ENTRANCE: string;
    CLUB_SHELTER_MAIN: string;
    CLUB_SHELTER_TOILETS: string;

    BAKER_STREET_12_GF: string;
    BAKER_STREET_12_F1_HALL: string;
    BAKER_STREET_12_F1_APT: string;
    BAKER_STREET_12_F2_HALL: string;
    BAKER_STREET_12_F2_APT: string;
    BAKER_STREET_12_F3_HALL: string;
    BAKER_STREET_12_F3_APT: string;
    BAKER_STREET_12_F4_HALL: string;
    BAKER_STREET_12_F4_APT: string;

    CAR_SHACK: string;

    YUM_MART_STORE: string;
    YUM_MART_OFFICE: string;

    SARDINE_STUDIOS_HALL_GF: string;
    SARDINE_STUDIOS_COMMUNAL_SPACE: string;
    SARDINE_STUDIOS_HALL_F1: string;
    SARDINE_STUDIOS_CORRIDOR_F1: string;
    SARDINE_STUDIOS_F1_APT1: string;
    SARDINE_STUDIOS_F1_APT2: string;
    SARDINE_STUDIOS_F1_APT3: string;
    SARDINE_STUDIOS_HALL_F2: string;
    SARDINE_STUDIOS_HALL_F3: string;

    GREY_BUILDING_GF_LOBBY: string;
    GREY_BUILDING_GF_HALL_LEFT: string;
    GREY_BUILDING_GF_HALL_RIGHT: string;
    GREY_BUILDING_GF_APT1: string;
    GREY_BUILDING_GF_APT1_TOILET: string;
    GREY_BUILDING_GF_APT1_BEDROOM: string;
    GREY_BUILDING_GF_APT2: string;
    GREY_BUILDING_GF_APT2_TOILET: string;
    GREY_BUILDING_GF_APT2_BEDROOM: string;
    GREY_BUILDING_GF_APT3: string;
    GREY_BUILDING_GF_APT3_TOILET: string;
    GREY_BUILDING_GF_APT3_BEDROOM: string;
    GREY_BUILDING_GF_APT4: string;
    GREY_BUILDING_GF_APT4_TOILET: string;
    GREY_BUILDING_GF_APT4_BEDROOM: string;
    GREY_BUILDING_GF_APT5: string;
    GREY_BUILDING_GF_APT5_TOILET: string;
    GREY_BUILDING_GF_APT5_BEDROOM: string;
    GREY_BUILDING_GF_APT6: string;
    GREY_BUILDING_GF_APT6_TOILET: string;
    GREY_BUILDING_GF_APT6_BEDROOM: string;
    GREY_BUILDING_F1_LOBBY: string;
    GREY_BUILDING_F1_HALL_LEFT: string;
    GREY_BUILDING_F1_HALL_RIGHT: string;
    GREY_BUILDING_F1_APT1: string;
    GREY_BUILDING_F1_APT1_TOILET: string;
    GREY_BUILDING_F1_APT1_BEDROOM: string;
    GREY_BUILDING_F1_APT2: string;
    GREY_BUILDING_F1_APT2_TOILET: string;
    GREY_BUILDING_F1_APT2_BEDROOM: string;
    GREY_BUILDING_F1_APT3: string;
    GREY_BUILDING_F1_APT3_TOILET: string;
    GREY_BUILDING_F1_APT3_BEDROOM: string;
    GREY_BUILDING_F1_APT4: string;
    GREY_BUILDING_F1_APT4_TOILET: string;
    GREY_BUILDING_F1_APT4_BEDROOM: string;
    GREY_BUILDING_F1_APT5: string;
    GREY_BUILDING_F1_APT5_TOILET: string;
    GREY_BUILDING_F1_APT5_BEDROOM: string;
    GREY_BUILDING_F1_APT6: string;
    GREY_BUILDING_F1_APT6_TOILET: string;
    GREY_BUILDING_F1_APT6_BEDROOM: string;
    GREY_BUILDING_F2_LOBBY: string;
    GREY_BUILDING_F2_HALL_LEFT: string;
    GREY_BUILDING_F2_APT1: string;
    GREY_BUILDING_F2_APT1_TOILET: string;
    GREY_BUILDING_F2_APT1_BEDROOM: string;
    GREY_BUILDING_F2_APT2: string;
    GREY_BUILDING_F2_APT2_TOILET: string;
    GREY_BUILDING_F2_APT2_BEDROOM: string;
    GREY_BUILDING_F2_APT3: string;
    GREY_BUILDING_F2_APT3_TOILET: string;
    GREY_BUILDING_F2_APT3_BEDROOM: string;
    GREY_BUILDING_F3_LOBBY: string;
    GREY_BUILDING_F3_HALL_LEFT: string;
    GREY_BUILDING_F3_HALL_RIGHT: string;
    GREY_BUILDING_F3_APT1: string;
    GREY_BUILDING_F3_APT1_TOILET: string;
    GREY_BUILDING_F3_APT1_BEDROOM: string;
    GREY_BUILDING_F3_APT2: string;
    GREY_BUILDING_F3_APT2_TOILET: string;
    GREY_BUILDING_F3_APT2_BEDROOM: string;
    GREY_BUILDING_F3_APT3: string;
    GREY_BUILDING_F3_APT3_TOILET: string;
    GREY_BUILDING_F3_APT3_BEDROOM: string;
    GREY_BUILDING_F3_APT4: string;
    GREY_BUILDING_F3_APT4_TOILET: string;
    GREY_BUILDING_F3_APT4_BEDROOM: string;
    GREY_BUILDING_F3_APT5: string;
    GREY_BUILDING_F3_APT5_TOILET: string;
    GREY_BUILDING_F3_APT5_BEDROOM: string;
    GREY_BUILDING_F3_APT6: string;
    GREY_BUILDING_F3_APT6_TOILET: string;
    GREY_BUILDING_F3_APT6_BEDROOM: string;
    GREY_BUILDING_F4_LOBBY: string;
}
type MasterRoomsMapIds = NeighbourhoodMapIds & {
    MASTER_ROOM_CHARACTERS: string;
    MASTER_ROOM_CARS: string;

}
type CinematicMapsMapIds = NeighbourhoodMapIds & {
    CINEMATIC_INTRO_MAP_1: string;
    CINEMATIC_INTRO_MAP_2: string;
}

export const MAP_IDS: MapIds = {
    LEONARD_HEIGHTS: {
        NEIGHBOURHOOD_KEY: NEIGHBOURHOOD_IDS.LEONARD_HEIGHTS,
        //#region Leonard Heights
        HOTEL_THE_TWO_TOWERS_LOBBY: "HOTEL_THE_TWO_TOWERS_LOBBY",

        CLUB_SHELTER_ENTRANCE: "CLUB_SHELTER_ENTRANCE",
        CLUB_SHELTER_MAIN: "CLUB_SHELTER_MAIN",
        CLUB_SHELTER_TOILETS: "CLUB_SHELTER_TOILETS",

        BAKER_STREET_12_GF: "BAKER_STREET_12_GF",
        BAKER_STREET_12_F1_HALL: "BAKER_STREET_12_F1_HALL",
        BAKER_STREET_12_F1_APT: "BAKER_STREET_12_F1_APT",
        BAKER_STREET_12_F2_HALL: "BAKER_STREET_12_F2_HALL",
        BAKER_STREET_12_F2_APT: "BAKER_STREET_12_F2_APT",
        BAKER_STREET_12_F3_HALL: "BAKER_STREET_12_F3_HALL",
        BAKER_STREET_12_F3_APT: "BAKER_STREET_12_F3_APT",
        BAKER_STREET_12_F4_HALL: "BAKER_STREET_12_F4_HALL",
        BAKER_STREET_12_F4_APT: "BAKER_STREET_12_F4_APT",

        CAR_SHACK: "CAR_SHACK",

        YUM_MART_STORE: "YUM_MART_STORE",
        YUM_MART_OFFICE: "YUM_MART_OFFICE",

        SARDINE_STUDIOS_HALL_GF: "SARDINE_STUDIOS_HALL_GF",
        SARDINE_STUDIOS_COMMUNAL_SPACE: "SARDINE_STUDIOS_COMMUNAL_SPACE",
        SARDINE_STUDIOS_HALL_F1: "SARDINE_STUDIOS_HALL_F1",
        SARDINE_STUDIOS_CORRIDOR_F1: "SARDINE_STUDIOS_CORRIDOR_F1",
        SARDINE_STUDIOS_F1_APT1: "SARDINE_STUDIOS_F1_APT1",
        SARDINE_STUDIOS_F1_APT2: "SARDINE_STUDIOS_F1_APT2",
        SARDINE_STUDIOS_F1_APT3: "SARDINE_STUDIOS_F1_APT3",
        SARDINE_STUDIOS_HALL_F2: "SARDINE_STUDIOS_HALL_F2",
        SARDINE_STUDIOS_HALL_F3: "SARDINE_STUDIOS_HALL_F3",

        GREY_BUILDING_GF_LOBBY: "GREY_BUILDING_GF_LOBBY",
        GREY_BUILDING_GF_HALL_LEFT: "GREY_BUILDING_GF_HALL_LEFT",
        GREY_BUILDING_GF_HALL_RIGHT: "GREY_BUILDING_GF_HALL_RIGHT",
        GREY_BUILDING_GF_APT1: "GREY_BUILDING_GF_APT1",
        GREY_BUILDING_GF_APT1_TOILET: "GREY_BUILDING_GF_APT1_TOILET",
        GREY_BUILDING_GF_APT1_BEDROOM: "GREY_BUILDING_GF_APT1_BEDROOM",
        GREY_BUILDING_GF_APT2: "GREY_BUILDING_GF_APT2",
        GREY_BUILDING_GF_APT2_TOILET: "GREY_BUILDING_GF_APT2_TOILET",
        GREY_BUILDING_GF_APT2_BEDROOM: "GREY_BUILDING_GF_APT2_BEDROOM",
        GREY_BUILDING_GF_APT3: "GREY_BUILDING_GF_APT3",
        GREY_BUILDING_GF_APT3_TOILET: "GREY_BUILDING_GF_APT3_TOILET",
        GREY_BUILDING_GF_APT3_BEDROOM: "GREY_BUILDING_GF_APT3_BEDROOM",
        GREY_BUILDING_GF_APT4: "GREY_BUILDING_GF_APT4",
        GREY_BUILDING_GF_APT4_TOILET: "GREY_BUILDING_GF_APT4_TOILET",
        GREY_BUILDING_GF_APT4_BEDROOM: "GREY_BUILDING_GF_APT4_BEDROOM",
        GREY_BUILDING_GF_APT5: "GREY_BUILDING_GF_APT5",
        GREY_BUILDING_GF_APT5_TOILET: "GREY_BUILDING_GF_APT5_TOILET",
        GREY_BUILDING_GF_APT5_BEDROOM: "GREY_BUILDING_GF_APT5_BEDROOM",
        GREY_BUILDING_GF_APT6: "GREY_BUILDING_GF_APT6",
        GREY_BUILDING_GF_APT6_TOILET: "GREY_BUILDING_GF_APT6_TOILET",
        GREY_BUILDING_GF_APT6_BEDROOM: "GREY_BUILDING_GF_APT6_BEDROOM",
        GREY_BUILDING_F1_LOBBY: "GREY_BUILDING_F1_LOBBY",
        GREY_BUILDING_F1_HALL_LEFT: "GREY_BUILDING_F1_HALL_LEFT",
        GREY_BUILDING_F1_HALL_RIGHT: "GREY_BUILDING_F1_HALL_RIGHT",
        GREY_BUILDING_F1_APT1: "GREY_BUILDING_F1_APT1",
        GREY_BUILDING_F1_APT1_TOILET: "GREY_BUILDING_F1_APT1_TOILET",
        GREY_BUILDING_F1_APT1_BEDROOM: "GREY_BUILDING_F1_APT1_BEDROOM",
        GREY_BUILDING_F1_APT2: "GREY_BUILDING_F1_APT2",
        GREY_BUILDING_F1_APT2_TOILET: "GREY_BUILDING_F1_APT2_TOILET",
        GREY_BUILDING_F1_APT2_BEDROOM: "GREY_BUILDING_F1_APT2_BEDROOM",
        GREY_BUILDING_F1_APT3: "GREY_BUILDING_F1_APT3",
        GREY_BUILDING_F1_APT3_TOILET: "GREY_BUILDING_F1_APT3_TOILET",
        GREY_BUILDING_F1_APT3_BEDROOM: "GREY_BUILDING_F1_APT3_BEDROOM",
        GREY_BUILDING_F1_APT4: "GREY_BUILDING_F1_APT4",
        GREY_BUILDING_F1_APT4_TOILET: "GREY_BUILDING_F1_APT4_TOILET",
        GREY_BUILDING_F1_APT4_BEDROOM: "GREY_BUILDING_F1_APT4_BEDROOM",
        GREY_BUILDING_F1_APT5: "GREY_BUILDING_F1_APT5",
        GREY_BUILDING_F1_APT5_TOILET: "GREY_BUILDING_F1_APT5_TOILET",
        GREY_BUILDING_F1_APT5_BEDROOM: "GREY_BUILDING_F1_APT5_BEDROOM",
        GREY_BUILDING_F1_APT6: "GREY_BUILDING_F1_APT6",
        GREY_BUILDING_F1_APT6_TOILET: "GREY_BUILDING_F1_APT6_TOILET",
        GREY_BUILDING_F1_APT6_BEDROOM: "GREY_BUILDING_F1_APT6_BEDROOM",
        GREY_BUILDING_F2_LOBBY: "GREY_BUILDING_F2_LOBBY",
        GREY_BUILDING_F2_HALL_LEFT: "GREY_BUILDING_F2_HALL_LEFT",
        GREY_BUILDING_F2_APT1: "GREY_BUILDING_F2_APT1",
        GREY_BUILDING_F2_APT1_TOILET: "GREY_BUILDING_F2_APT1_TOILET",
        GREY_BUILDING_F2_APT1_BEDROOM: "GREY_BUILDING_F2_APT1_BEDROOM",
        GREY_BUILDING_F2_APT2: "GREY_BUILDING_F2_APT2",
        GREY_BUILDING_F2_APT2_TOILET: "GREY_BUILDING_F2_APT2_TOILET",
        GREY_BUILDING_F2_APT2_BEDROOM: "GREY_BUILDING_F2_APT2_BEDROOM",
        GREY_BUILDING_F2_APT3: "GREY_BUILDING_F2_APT3",
        GREY_BUILDING_F2_APT3_TOILET: "GREY_BUILDING_F2_APT3_TOILET",
        GREY_BUILDING_F2_APT3_BEDROOM: "GREY_BUILDING_F2_APT3_BEDROOM",
        GREY_BUILDING_F3_LOBBY: "GREY_BUILDING_F3_LOBBY",
        GREY_BUILDING_F3_HALL_LEFT: "GREY_BUILDING_F3_HALL_LEFT",
        GREY_BUILDING_F3_HALL_RIGHT: "GREY_BUILDING_F3_HALL_RIGHT",
        GREY_BUILDING_F3_APT1: "GREY_BUILDING_F3_APT1",
        GREY_BUILDING_F3_APT1_TOILET: "GREY_BUILDING_F3_APT1_TOILET",
        GREY_BUILDING_F3_APT1_BEDROOM: "GREY_BUILDING_F3_APT1_BEDROOM",
        GREY_BUILDING_F3_APT2: "GREY_BUILDING_F3_APT2",
        GREY_BUILDING_F3_APT2_TOILET: "GREY_BUILDING_F3_APT2_TOILET",
        GREY_BUILDING_F3_APT2_BEDROOM: "GREY_BUILDING_F3_APT2_BEDROOM",
        GREY_BUILDING_F3_APT3: "GREY_BUILDING_F3_APT3",
        GREY_BUILDING_F3_APT3_TOILET: "GREY_BUILDING_F3_APT3_TOILET",
        GREY_BUILDING_F3_APT3_BEDROOM: "GREY_BUILDING_F3_APT3_BEDROOM",
        GREY_BUILDING_F3_APT4: "GREY_BUILDING_F3_APT4",
        GREY_BUILDING_F3_APT4_TOILET: "GREY_BUILDING_F3_APT4_TOILET",
        GREY_BUILDING_F3_APT4_BEDROOM: "GREY_BUILDING_F3_APT4_BEDROOM",
        GREY_BUILDING_F3_APT5: "GREY_BUILDING_F3_APT5",
        GREY_BUILDING_F3_APT5_TOILET: "GREY_BUILDING_F3_APT5_TOILET",
        GREY_BUILDING_F3_APT5_BEDROOM: "GREY_BUILDING_F3_APT5_BEDROOM",
        GREY_BUILDING_F3_APT6: "GREY_BUILDING_F3_APT6",
        GREY_BUILDING_F3_APT6_TOILET: "GREY_BUILDING_F3_APT6_TOILET",
        GREY_BUILDING_F3_APT6_BEDROOM: "GREY_BUILDING_F3_APT6_BEDROOM",
        GREY_BUILDING_F4_LOBBY: "GREY_BUILDING_F4_LOBBY",
        //#endregion
    },

    MASTER_ROOMS: {
        NEIGHBOURHOOD_KEY: NEIGHBOURHOOD_IDS.MASTER_ROOMS,
        //#region Master Rooms
        MASTER_ROOM_CHARACTERS: "MASTER_ROOM_CHARACTERS",
        MASTER_ROOM_CARS: "MASTER_ROOM_CARS",
        //#endregion
    },

    CINEMATIC_MAPS: {
        NEIGHBOURHOOD_KEY: NEIGHBOURHOOD_IDS.CINEMATIC_MAPS,
        //#region Cinematic maps
        CINEMATIC_INTRO_MAP_1: "CINEMATIC_INTRO_MAP_1",
        CINEMATIC_INTRO_MAP_2: "CINEMATIC_INTRO_MAP_2"
        //#endregion
    }
}

export const determineMapNeighbourhood = ( mapKey: string ): string => {
    let neighbourhoodId = null

    Object.keys( MAP_IDS ).forEach( ( neighbourhoodKey ) => {
        const neighbourhoodMapIds = MAP_IDS[neighbourhoodKey] as NeighbourhoodMapIds;
        if ( Object.values( neighbourhoodMapIds ).includes( mapKey ) ) {
            neighbourhoodId = neighbourhoodMapIds.NEIGHBOURHOOD_KEY;
        }
    } )
    if ( neighbourhoodId == null ) console.error( `No neighbourhood could be determined for map ${mapKey}` );
    return neighbourhoodId;
}