export const DOORKEY_GREY_BUILDING_F2_LEFT_HALL = "DOORKEY_GREY_BUILDING_F2_LOBBY_LEFT_HALL";
export const DOORKEY_GREY_BUILDING_F2_RIGHT_HALL = "DOORKEY_GREY_BUILDING_F2_LOBBY_LEFT_HALL";

export const DOORKEY_GREY_BUILDING_F2_APT1 = "DOORKEY_GREY_BUILDING_F2_APT1";
export const DOORKEY_GREY_BUILDING_F2_APT2 = "DOORKEY_GREY_BUILDING_F2_APT2";
export const DOORKEY_GREY_BUILDING_F2_APT3 = "DOORKEY_GREY_BUILDING_F2_APT3";
export const DOORKEY_GREY_BUILDING_F2_APT4 = "DOORKEY_GREY_BUILDING_F2_APT4";
export const DOORKEY_GREY_BUILDING_F2_APT5 = "DOORKEY_GREY_BUILDING_F2_APT5";
export const DOORKEY_GREY_BUILDING_F2_APT6 = "DOORKEY_GREY_BUILDING_F2_APT6";

export const DOORKEY_GREY_BUILDING_F2_APT1_TOILET = "DOORKEY_GREY_BUILDING_F2_APT1_TOILET";
export const DOORKEY_GREY_BUILDING_F2_APT1_BEDROOM = "DOORKEY_GREY_BUILDING_F2_APT1_BEDROOM";

export const DOORKEY_GREY_BUILDING_F2_APT2_TOILET = "DOORKEY_GREY_BUILDING_F2_APT2_TOILET";
export const DOORKEY_GREY_BUILDING_F2_APT2_BEDROOM = "DOORKEY_GREY_BUILDING_F2_APT2_BEDROOM";

export const DOORKEY_GREY_BUILDING_F2_APT3_TOILET = "DOORKEY_GREY_BUILDING_F2_APT3_TOILET";
export const DOORKEY_GREY_BUILDING_F2_APT3_BEDROOM = "DOORKEY_GREY_BUILDING_F2_APT3_BEDROOM";