export type CutsceneIds = {
    INTRO_CUTSCENE: string;

    RANDOM_ENCOUNTER_1: string;
    RANDOM_ENCOUNTER_2: string;
    RANDOM_ENCOUNTER_3: string;
    RANDOM_ENCOUNTER_4: string;
    RANDOM_ENCOUNTER_5: string;
    RANDOM_ENCOUNTER_6: string;
    RANDOM_ENCOUNTER_7: string;
    RANDOM_ENCOUNTER_8: string;

    A3_ROBOT_RECEPTIONIST: string;
    A3_ROBOT_COOK: string;
    A3_MONKEY_COOK: string;

    B3_GUY_WHO_LOST_HIS_KEYS: string;

    B4_WHOLESOME_LIFTER: string;

    C1_FIND_LOST_KEYS: string;

    C2_BS12_APT4_RESIDENT: string;
    C2_BS12_APT2_ROBOT_1: string;
    C2_BS12_APT2_ROBOT_2: string;

    C3_CAR_SHACK_BOSS: string;
    C3_CAR_SHACK_MECHANIC: string;

    C4_YUM_MART_OFFICE_GUY: string;

    D1_FRIENDLY_CHAD: string;
    D1_WHOLESOME_LIFTER: string;

    D2_WHOLESOME_LIFTER: string;
    D2_LOOKING_FOR_APPARTMENT_LADY: string;

    D2_SARSTUD_COMMUNAL_SPACE_GUY1: string;
    D2_SARSTUD_COMMUNAL_SPACE_WOMAN1: string;
    D2_SARSTUD_COMMUNAL_SPACE_ROBOT1: string;
    D2_SARSTUD_F1_A1_ROBOT1: string;
    D2_SARSTUD_F1_A1_POLICEWOMAN1: string;

    E4_WHOLESOME_LIFTER: string;
}

export const CUTSCENE_IDS: CutsceneIds = {
    //#region Cinematic csevent ids
    INTRO_CUTSCENE: "ID_INTRO_CUTSCENE",
    //#endregion
    //#region Random encounter csevent ids
    RANDOM_ENCOUNTER_1: "ID_CUTSCENE_RANDOM_ENCOUNTER_1",
    RANDOM_ENCOUNTER_2: "ID_CUTSCENE_RANDOM_ENCOUNTER_2",
    RANDOM_ENCOUNTER_3: "ID_CUTSCENE_RANDOM_ENCOUNTER_3",
    RANDOM_ENCOUNTER_4: "ID_CUTSCENE_RANDOM_ENCOUNTER_4",
    RANDOM_ENCOUNTER_5: "ID_CUTSCENE_RANDOM_ENCOUNTER_5",
    RANDOM_ENCOUNTER_6: "ID_CUTSCENE_RANDOM_ENCOUNTER_6",
    RANDOM_ENCOUNTER_7: "ID_CUTSCENE_RANDOM_ENCOUNTER_7",
    RANDOM_ENCOUNTER_8: "ID_CUTSCENE_RANDOM_ENCOUNTER_8",
    //#endregion
    //#region A3 csevent ids
    A3_ROBOT_RECEPTIONIST: "ID_CUTSCENE_A3_ROBOT_RECEPTIONIST",
    A3_ROBOT_COOK: "ID_CUTSCENE_A3_ROBOT_COOK",
    A3_MONKEY_COOK: "ID_CUTSCENE_A3_MONKEY_COOK",
    //#endregion
    //#region B3 csevent ids
    B3_GUY_WHO_LOST_HIS_KEYS: "ID_CSEVENT_B3_GUY_WHO_LOST_HIS_KEYS",
    //#endregion
    //#region B4 csevent ids
    B4_WHOLESOME_LIFTER: "ID_CSEVENT_B4_WHOLESOME_LIFTER",
    //#endregion
    //#region C1 csevent ids
    C1_FIND_LOST_KEYS: "ID_CSEVENT_C1_FIND_LOST_KEYS",
    //#endregion
    //#region C2 csevent ids
    C2_BS12_APT4_RESIDENT: "ID_CSEVENT_C2_BS12_APT4_RESIDENT",
    C2_BS12_APT2_ROBOT_1: "ID_CSEVENT_C2_BS12_APT2_ROBOT_1",
    C2_BS12_APT2_ROBOT_2: "ID_CSEVENT_C2_BS12_APT2_ROBOT_2",
    //#endregion
    //#region C3 csevent ids
    C3_CAR_SHACK_BOSS: "ID_CSEVENT_C3_CAR_SHACK_BOSS",
    C3_CAR_SHACK_MECHANIC: "ID_CSEVENT_C3_CAR_SHACK_MECHANIC",
    //#endregion
    //#region C4 csevent idsc
    C4_YUM_MART_OFFICE_GUY: "ID_CSEVENT_C4_YUM_MART_OFFICE_GUY",
    //#endregion
    //#region D1 csevent ids
    D1_FRIENDLY_CHAD: "ID_CSEVENT_D1_FRIENDLY_CHAD",
    D1_WHOLESOME_LIFTER: "ID_CSEVENT_D1_WHOLESOME_LIFTER",
    //#endregion
    //#region D2 csevent ids
    D2_WHOLESOME_LIFTER: "ID_CSEVENT_D2_INTERACTION_WHOLESOME_LIFTER",
    D2_LOOKING_FOR_APPARTMENT_LADY: "ID_CSEVENT_D2_LOOKING_FOR_APPARTMENT_LADY",

    D2_SARSTUD_COMMUNAL_SPACE_GUY1: "ID_CSEVENT_D2_COMMUNAL_SPACE_GUY1",
    D2_SARSTUD_COMMUNAL_SPACE_WOMAN1: "ID_CSEVENT_D2_COMMUNAL_SPACE_WOMAN1",
    D2_SARSTUD_COMMUNAL_SPACE_ROBOT1: "ID_CSEVENT_D2_COMMUNAL_SPACE_ROBOT1",
    D2_SARSTUD_F1_A1_ROBOT1: "ID_CSEVENT_D2_F1_A1_ROBOT1",
    D2_SARSTUD_F1_A1_POLICEWOMAN1: "ID_CSEVENT_D2_F1_A1_POLICEWOMAN1",
    //#endregion
    //#region E4 csevent ids
    E4_WHOLESOME_LIFTER: "ID_CSEVENT_E4_WHOLESOME_LIFTER",
    //#endregion
}