import { createDoorEventChain } from "../../factories/eventFactory";
import type { DoorEventChain } from "../../models/eventChains/DoorEventChain";
import { MAP_IDS } from "../mapResources/mapIds";
import { DOOR_IDS } from "./doorIds";

export const DOOR_EVENT_CHAINS: { [key in string]: DoorEventChain } = {
    //#region A3 door events
    [DOOR_IDS.TWO_TOWERS_MAIN_DOOR]: createDoorEventChain( MAP_IDS.LEONARD_HEIGHTS.HOTEL_THE_TWO_TOWERS_LOBBY, MAP_IDS.LEONARD_HEIGHTS.NEIGHBOURHOOD_KEY, DOOR_IDS.TWO_TOWERS_MAIN_DOOR ),
    //#endregion
    //#region B4 door events
    [DOOR_IDS.CLUBSHELTER_MAIN_FRONT_DOOR]: createDoorEventChain( MAP_IDS.LEONARD_HEIGHTS.NEIGHBOURHOOD_KEY, MAP_IDS.LEONARD_HEIGHTS.CLUB_SHELTER_ENTRANCE, DOOR_IDS.CLUBSHELTER_MAIN_FRONT_DOOR ),
    [DOOR_IDS.CLUBSHELTER_MAIN_INNER_DOOR]: createDoorEventChain( MAP_IDS.LEONARD_HEIGHTS.CLUB_SHELTER_ENTRANCE, MAP_IDS.LEONARD_HEIGHTS.CLUB_SHELTER_MAIN, DOOR_IDS.CLUBSHELTER_MAIN_INNER_DOOR ),
    [DOOR_IDS.CLUBSHELTER_TOILET_DOOR]: createDoorEventChain( MAP_IDS.LEONARD_HEIGHTS.CLUB_SHELTER_MAIN, MAP_IDS.LEONARD_HEIGHTS.CLUB_SHELTER_TOILETS, DOOR_IDS.CLUBSHELTER_TOILET_DOOR ),
    //#endregion
    //#region C2 door events
    [DOOR_IDS.BAKER_STREET_12_FRONT_DOOR]: createDoorEventChain( MAP_IDS.LEONARD_HEIGHTS.NEIGHBOURHOOD_KEY, MAP_IDS.LEONARD_HEIGHTS.BAKER_STREET_12_GF, DOOR_IDS.BAKER_STREET_12_FRONT_DOOR ),
    [DOOR_IDS.BAKER_STREET_12_STAIRS_GF]: createDoorEventChain( MAP_IDS.LEONARD_HEIGHTS.BAKER_STREET_12_GF, MAP_IDS.LEONARD_HEIGHTS.BAKER_STREET_12_F1_HALL, DOOR_IDS.BAKER_STREET_12_STAIRS_GF ),
    [DOOR_IDS.BAKER_STREET_12_APT_F1]: createDoorEventChain( MAP_IDS.LEONARD_HEIGHTS.BAKER_STREET_12_F1_HALL, MAP_IDS.LEONARD_HEIGHTS.BAKER_STREET_12_F1_APT, DOOR_IDS.BAKER_STREET_12_APT_F1 ),
    [DOOR_IDS.BAKER_STREET_12_STAIRS_F1]: createDoorEventChain( MAP_IDS.LEONARD_HEIGHTS.BAKER_STREET_12_F1_HALL, MAP_IDS.LEONARD_HEIGHTS.BAKER_STREET_12_F2_HALL, DOOR_IDS.BAKER_STREET_12_STAIRS_F1 ),
    [DOOR_IDS.BAKER_STREET_12_APT_F2]: createDoorEventChain( MAP_IDS.LEONARD_HEIGHTS.BAKER_STREET_12_F2_HALL, MAP_IDS.LEONARD_HEIGHTS.BAKER_STREET_12_F2_APT, DOOR_IDS.BAKER_STREET_12_APT_F2 ),
    [DOOR_IDS.BAKER_STREET_12_STAIRS_F2]: createDoorEventChain( MAP_IDS.LEONARD_HEIGHTS.BAKER_STREET_12_F2_HALL, MAP_IDS.LEONARD_HEIGHTS.BAKER_STREET_12_F3_HALL, DOOR_IDS.BAKER_STREET_12_STAIRS_F2 ),
    [DOOR_IDS.BAKER_STREET_12_APT_F3]: createDoorEventChain( MAP_IDS.LEONARD_HEIGHTS.BAKER_STREET_12_F3_HALL, MAP_IDS.LEONARD_HEIGHTS.BAKER_STREET_12_F3_APT, DOOR_IDS.BAKER_STREET_12_APT_F3 ),
    [DOOR_IDS.BAKER_STREET_12_STAIRS_F3]: createDoorEventChain( MAP_IDS.LEONARD_HEIGHTS.BAKER_STREET_12_F3_HALL, MAP_IDS.LEONARD_HEIGHTS.BAKER_STREET_12_F4_HALL, DOOR_IDS.BAKER_STREET_12_STAIRS_F3 ),
    [DOOR_IDS.BAKER_STREET_12_APT_F4]: createDoorEventChain( MAP_IDS.LEONARD_HEIGHTS.BAKER_STREET_12_F4_HALL, MAP_IDS.LEONARD_HEIGHTS.BAKER_STREET_12_F4_APT, DOOR_IDS.BAKER_STREET_12_APT_F4 ),
    //#endregion
    //#region C3 door events
    [DOOR_IDS.CAR_SHACK_FRONT_DOOR]: createDoorEventChain( MAP_IDS.LEONARD_HEIGHTS.NEIGHBOURHOOD_KEY, MAP_IDS.LEONARD_HEIGHTS.CAR_SHACK, DOOR_IDS.CAR_SHACK_FRONT_DOOR ),
    //#endregion
    //#region C4 door events
    [DOOR_IDS.YUM_MART_FRONT_DOOR]: createDoorEventChain( MAP_IDS.LEONARD_HEIGHTS.NEIGHBOURHOOD_KEY, MAP_IDS.LEONARD_HEIGHTS.YUM_MART_STORE, DOOR_IDS.YUM_MART_FRONT_DOOR ),
    [DOOR_IDS.YUM_MART_DOOR_1]: createDoorEventChain( MAP_IDS.LEONARD_HEIGHTS.YUM_MART_STORE, MAP_IDS.LEONARD_HEIGHTS.YUM_MART_OFFICE, DOOR_IDS.YUM_MART_DOOR_1 ),
    //#endregion
    //#region D2 door events
    [DOOR_IDS.SARDINE_STUDIOS_FRONT_DOOR]: createDoorEventChain( MAP_IDS.LEONARD_HEIGHTS.NEIGHBOURHOOD_KEY, MAP_IDS.LEONARD_HEIGHTS.SARDINE_STUDIOS_HALL_GF, DOOR_IDS.SARDINE_STUDIOS_FRONT_DOOR ),
    [DOOR_IDS.SARDINE_STUDIOS_DOOR_STAIRS_F1]: createDoorEventChain( MAP_IDS.LEONARD_HEIGHTS.SARDINE_STUDIOS_HALL_GF, MAP_IDS.LEONARD_HEIGHTS.SARDINE_STUDIOS_HALL_F1, DOOR_IDS.SARDINE_STUDIOS_DOOR_STAIRS_F1 ),
    [DOOR_IDS.SARDINE_STUDIOS_DOOR_STAIRS_F2]: createDoorEventChain( MAP_IDS.LEONARD_HEIGHTS.SARDINE_STUDIOS_HALL_F1, MAP_IDS.LEONARD_HEIGHTS.SARDINE_STUDIOS_HALL_F2, DOOR_IDS.SARDINE_STUDIOS_DOOR_STAIRS_F2 ),
    [DOOR_IDS.SARDINE_STUDIOS_DOOR_STAIRS_TOP]: createDoorEventChain( MAP_IDS.LEONARD_HEIGHTS.SARDINE_STUDIOS_HALL_F2, MAP_IDS.LEONARD_HEIGHTS.SARDINE_STUDIOS_HALL_F3, DOOR_IDS.SARDINE_STUDIOS_DOOR_STAIRS_TOP ),
    [DOOR_IDS.SARDINE_STUDIOS_COMMON_AREA]: createDoorEventChain( MAP_IDS.LEONARD_HEIGHTS.SARDINE_STUDIOS_HALL_GF, MAP_IDS.LEONARD_HEIGHTS.SARDINE_STUDIOS_COMMUNAL_SPACE, DOOR_IDS.SARDINE_STUDIOS_COMMON_AREA ),
    [DOOR_IDS.SARDINE_STUDIOS_DOOR_F1_HALL]: createDoorEventChain( MAP_IDS.LEONARD_HEIGHTS.SARDINE_STUDIOS_HALL_F1, MAP_IDS.LEONARD_HEIGHTS.SARDINE_STUDIOS_CORRIDOR_F1, DOOR_IDS.SARDINE_STUDIOS_DOOR_F1_HALL ),
    [DOOR_IDS.SARDINE_STUDIOS_DOOR_F1_APP1]: createDoorEventChain( MAP_IDS.LEONARD_HEIGHTS.SARDINE_STUDIOS_CORRIDOR_F1, MAP_IDS.LEONARD_HEIGHTS.SARDINE_STUDIOS_F1_APT1, DOOR_IDS.SARDINE_STUDIOS_DOOR_F1_APP1 ),
    [DOOR_IDS.SARDINE_STUDIOS_DOOR_F1_APP2]: createDoorEventChain( MAP_IDS.LEONARD_HEIGHTS.SARDINE_STUDIOS_CORRIDOR_F1, MAP_IDS.LEONARD_HEIGHTS.SARDINE_STUDIOS_F1_APT2, DOOR_IDS.SARDINE_STUDIOS_DOOR_F1_APP2 ),
    [DOOR_IDS.SARDINE_STUDIOS_DOOR_F1_APP3]: createDoorEventChain( MAP_IDS.LEONARD_HEIGHTS.SARDINE_STUDIOS_CORRIDOR_F1, MAP_IDS.LEONARD_HEIGHTS.SARDINE_STUDIOS_F1_APT3, DOOR_IDS.SARDINE_STUDIOS_DOOR_F1_APP3 ),
    //#endregion
    //#region C4 door events
    [DOOR_IDS.GREY_BUILDING_FRONT_DOOR]: createDoorEventChain( MAP_IDS.LEONARD_HEIGHTS.NEIGHBOURHOOD_KEY, MAP_IDS.LEONARD_HEIGHTS.GREY_BUILDING_GF_LOBBY, DOOR_IDS.GREY_BUILDING_FRONT_DOOR ),
        //#region Grey building GF
        [DOOR_IDS.GREY_BUILDING_GF_LEFT_HALL]: createDoorEventChain( MAP_IDS.LEONARD_HEIGHTS.GREY_BUILDING_GF_LOBBY, MAP_IDS.LEONARD_HEIGHTS.GREY_BUILDING_GF_HALL_LEFT, DOOR_IDS.GREY_BUILDING_GF_LEFT_HALL ),
        [DOOR_IDS.GREY_BUILDING_GF_APT1]: createDoorEventChain( MAP_IDS.LEONARD_HEIGHTS.GREY_BUILDING_GF_HALL_LEFT, MAP_IDS.LEONARD_HEIGHTS.GREY_BUILDING_GF_APT1, DOOR_IDS.GREY_BUILDING_GF_APT1 ),
            //#region Grey building GF APT1
            [DOOR_IDS.GREY_BUILDING_GF_APT1_TOILET]: createDoorEventChain( MAP_IDS.LEONARD_HEIGHTS.GREY_BUILDING_GF_APT1, MAP_IDS.LEONARD_HEIGHTS.GREY_BUILDING_GF_APT1_TOILET, DOOR_IDS.GREY_BUILDING_GF_APT1_TOILET ),
            [DOOR_IDS.GREY_BUILDING_GF_APT1_BEDROOM]: createDoorEventChain( MAP_IDS.LEONARD_HEIGHTS.GREY_BUILDING_GF_APT1, MAP_IDS.LEONARD_HEIGHTS.GREY_BUILDING_GF_APT1_BEDROOM, DOOR_IDS.GREY_BUILDING_GF_APT1_BEDROOM ),
            //#endregion
        [DOOR_IDS.GREY_BUILDING_GF_APT2]: createDoorEventChain( MAP_IDS.LEONARD_HEIGHTS.GREY_BUILDING_GF_HALL_LEFT, MAP_IDS.LEONARD_HEIGHTS.GREY_BUILDING_GF_APT2, DOOR_IDS.GREY_BUILDING_GF_APT2 ),
            //#region Grey building GF APT2
            [DOOR_IDS.GREY_BUILDING_GF_APT2_TOILET]: createDoorEventChain( MAP_IDS.LEONARD_HEIGHTS.GREY_BUILDING_GF_APT2, MAP_IDS.LEONARD_HEIGHTS.GREY_BUILDING_GF_APT2_TOILET, DOOR_IDS.GREY_BUILDING_GF_APT2_TOILET ),
            [DOOR_IDS.GREY_BUILDING_GF_APT2_BEDROOM]: createDoorEventChain( MAP_IDS.LEONARD_HEIGHTS.GREY_BUILDING_GF_APT2, MAP_IDS.LEONARD_HEIGHTS.GREY_BUILDING_GF_APT2_BEDROOM, DOOR_IDS.GREY_BUILDING_GF_APT2_BEDROOM ),
            //#endregion
        [DOOR_IDS.GREY_BUILDING_GF_APT3]: createDoorEventChain( MAP_IDS.LEONARD_HEIGHTS.GREY_BUILDING_GF_HALL_LEFT, MAP_IDS.LEONARD_HEIGHTS.GREY_BUILDING_GF_APT3, DOOR_IDS.GREY_BUILDING_GF_APT3 ),
            //#region Grey building GF APT3
            [DOOR_IDS.GREY_BUILDING_GF_APT3_TOILET]: createDoorEventChain( MAP_IDS.LEONARD_HEIGHTS.GREY_BUILDING_GF_APT3, MAP_IDS.LEONARD_HEIGHTS.GREY_BUILDING_GF_APT3_TOILET, DOOR_IDS.GREY_BUILDING_GF_APT3_TOILET ),
            [DOOR_IDS.GREY_BUILDING_GF_APT3_BEDROOM]: createDoorEventChain( MAP_IDS.LEONARD_HEIGHTS.GREY_BUILDING_GF_APT3, MAP_IDS.LEONARD_HEIGHTS.GREY_BUILDING_GF_APT3_BEDROOM, DOOR_IDS.GREY_BUILDING_GF_APT3_BEDROOM ),
            //#endregion
        [DOOR_IDS.GREY_BUILDING_GF_RIGHT_HALL]: createDoorEventChain( MAP_IDS.LEONARD_HEIGHTS.GREY_BUILDING_GF_LOBBY, MAP_IDS.LEONARD_HEIGHTS.GREY_BUILDING_GF_HALL_RIGHT, DOOR_IDS.GREY_BUILDING_GF_RIGHT_HALL ),
        [DOOR_IDS.GREY_BUILDING_GF_APT4]: createDoorEventChain( MAP_IDS.LEONARD_HEIGHTS.GREY_BUILDING_GF_HALL_LEFT, MAP_IDS.LEONARD_HEIGHTS.GREY_BUILDING_GF_APT4, DOOR_IDS.GREY_BUILDING_GF_APT4 ),
            //#region Grey building GF APT4
            [DOOR_IDS.GREY_BUILDING_GF_APT4_TOILET]: createDoorEventChain( MAP_IDS.LEONARD_HEIGHTS.GREY_BUILDING_GF_APT4, MAP_IDS.LEONARD_HEIGHTS.GREY_BUILDING_GF_APT4_TOILET, DOOR_IDS.GREY_BUILDING_GF_APT4_TOILET ),
            [DOOR_IDS.GREY_BUILDING_GF_APT4_BEDROOM]: createDoorEventChain( MAP_IDS.LEONARD_HEIGHTS.GREY_BUILDING_GF_APT4, MAP_IDS.LEONARD_HEIGHTS.GREY_BUILDING_GF_APT4_BEDROOM, DOOR_IDS.GREY_BUILDING_GF_APT4_BEDROOM ),
            //#endregion
        [DOOR_IDS.GREY_BUILDING_GF_APT5]: createDoorEventChain( MAP_IDS.LEONARD_HEIGHTS.GREY_BUILDING_GF_HALL_LEFT, MAP_IDS.LEONARD_HEIGHTS.GREY_BUILDING_GF_APT5, DOOR_IDS.GREY_BUILDING_GF_APT5 ),
            //#region Grey building GF APT5
            [DOOR_IDS.GREY_BUILDING_GF_APT5_TOILET]: createDoorEventChain( MAP_IDS.LEONARD_HEIGHTS.GREY_BUILDING_GF_APT5, MAP_IDS.LEONARD_HEIGHTS.GREY_BUILDING_GF_APT5_TOILET, DOOR_IDS.GREY_BUILDING_GF_APT5_TOILET ),
            [DOOR_IDS.GREY_BUILDING_GF_APT5_BEDROOM]: createDoorEventChain( MAP_IDS.LEONARD_HEIGHTS.GREY_BUILDING_GF_APT5, MAP_IDS.LEONARD_HEIGHTS.GREY_BUILDING_GF_APT5_BEDROOM, DOOR_IDS.GREY_BUILDING_GF_APT5_BEDROOM ),
            //#endregion
        [DOOR_IDS.GREY_BUILDING_GF_APT6]: createDoorEventChain( MAP_IDS.LEONARD_HEIGHTS.GREY_BUILDING_GF_HALL_LEFT, MAP_IDS.LEONARD_HEIGHTS.GREY_BUILDING_GF_APT6, DOOR_IDS.GREY_BUILDING_GF_APT6 ),
            //#region Grey building GF APT6
            [DOOR_IDS.GREY_BUILDING_GF_APT6_TOILET]: createDoorEventChain( MAP_IDS.LEONARD_HEIGHTS.GREY_BUILDING_GF_APT6, MAP_IDS.LEONARD_HEIGHTS.GREY_BUILDING_GF_APT6_TOILET, DOOR_IDS.GREY_BUILDING_GF_APT6_TOILET ),
            [DOOR_IDS.GREY_BUILDING_GF_APT6_BEDROOM]: createDoorEventChain( MAP_IDS.LEONARD_HEIGHTS.GREY_BUILDING_GF_APT6, MAP_IDS.LEONARD_HEIGHTS.GREY_BUILDING_GF_APT6_BEDROOM, DOOR_IDS.GREY_BUILDING_GF_APT6_BEDROOM ),
            //#endregion
        //#endregion
        //#region Grey building F1
        [DOOR_IDS.GREY_BUILDING_F1_LEFT_HALL]: createDoorEventChain( MAP_IDS.LEONARD_HEIGHTS.GREY_BUILDING_F1_LOBBY, MAP_IDS.LEONARD_HEIGHTS.GREY_BUILDING_F1_HALL_LEFT, DOOR_IDS.GREY_BUILDING_F1_LEFT_HALL ),
        [DOOR_IDS.GREY_BUILDING_F1_APT1]: createDoorEventChain( MAP_IDS.LEONARD_HEIGHTS.GREY_BUILDING_F1_HALL_LEFT, MAP_IDS.LEONARD_HEIGHTS.GREY_BUILDING_F1_APT1, DOOR_IDS.GREY_BUILDING_F1_APT1 ),
            //#region Grey building F1 APT1
            [DOOR_IDS.GREY_BUILDING_F1_APT1_TOILET]: createDoorEventChain( MAP_IDS.LEONARD_HEIGHTS.GREY_BUILDING_F1_APT1, MAP_IDS.LEONARD_HEIGHTS.GREY_BUILDING_F1_APT1_TOILET, DOOR_IDS.GREY_BUILDING_F1_APT1_TOILET ),
            [DOOR_IDS.GREY_BUILDING_F1_APT1_BEDROOM]: createDoorEventChain( MAP_IDS.LEONARD_HEIGHTS.GREY_BUILDING_F1_APT1, MAP_IDS.LEONARD_HEIGHTS.GREY_BUILDING_F1_APT1_BEDROOM, DOOR_IDS.GREY_BUILDING_F1_APT1_BEDROOM ),
            //#endregion
        [DOOR_IDS.GREY_BUILDING_F1_APT2]: createDoorEventChain( MAP_IDS.LEONARD_HEIGHTS.GREY_BUILDING_F1_HALL_LEFT, MAP_IDS.LEONARD_HEIGHTS.GREY_BUILDING_F1_APT2, DOOR_IDS.GREY_BUILDING_F1_APT2 ),
            //#region Grey building F1 APT2
            [DOOR_IDS.GREY_BUILDING_F1_APT2_TOILET]: createDoorEventChain( MAP_IDS.LEONARD_HEIGHTS.GREY_BUILDING_F1_APT2, MAP_IDS.LEONARD_HEIGHTS.GREY_BUILDING_F1_APT2_TOILET, DOOR_IDS.GREY_BUILDING_F1_APT2_TOILET ),
            [DOOR_IDS.GREY_BUILDING_F1_APT2_BEDROOM]: createDoorEventChain( MAP_IDS.LEONARD_HEIGHTS.GREY_BUILDING_F1_APT2, MAP_IDS.LEONARD_HEIGHTS.GREY_BUILDING_F1_APT2_BEDROOM, DOOR_IDS.GREY_BUILDING_F1_APT2_BEDROOM ),
            //#endregion
        [DOOR_IDS.GREY_BUILDING_F1_APT3]: createDoorEventChain( MAP_IDS.LEONARD_HEIGHTS.GREY_BUILDING_F1_HALL_LEFT, MAP_IDS.LEONARD_HEIGHTS.GREY_BUILDING_F1_APT3, DOOR_IDS.GREY_BUILDING_F1_APT3 ),
            //#region Grey building F1 APT3
            [DOOR_IDS.GREY_BUILDING_F1_APT3_TOILET]: createDoorEventChain( MAP_IDS.LEONARD_HEIGHTS.GREY_BUILDING_F1_APT3, MAP_IDS.LEONARD_HEIGHTS.GREY_BUILDING_F1_APT3_TOILET, DOOR_IDS.GREY_BUILDING_F1_APT3_TOILET ),
            [DOOR_IDS.GREY_BUILDING_F1_APT3_BEDROOM]: createDoorEventChain( MAP_IDS.LEONARD_HEIGHTS.GREY_BUILDING_F1_APT3, MAP_IDS.LEONARD_HEIGHTS.GREY_BUILDING_F1_APT3_BEDROOM, DOOR_IDS.GREY_BUILDING_F1_APT3_BEDROOM ),
            //#endregion
        [DOOR_IDS.GREY_BUILDING_F1_RIGHT_HALL]: createDoorEventChain( MAP_IDS.LEONARD_HEIGHTS.GREY_BUILDING_F1_LOBBY, MAP_IDS.LEONARD_HEIGHTS.GREY_BUILDING_F1_HALL_RIGHT, DOOR_IDS.GREY_BUILDING_F1_RIGHT_HALL ),
        [DOOR_IDS.GREY_BUILDING_F1_APT4]: createDoorEventChain( MAP_IDS.LEONARD_HEIGHTS.GREY_BUILDING_F1_HALL_LEFT, MAP_IDS.LEONARD_HEIGHTS.GREY_BUILDING_F1_APT4, DOOR_IDS.GREY_BUILDING_F1_APT4 ),
            //#region Grey building F1 APT4
            [DOOR_IDS.GREY_BUILDING_F1_APT4_TOILET]: createDoorEventChain( MAP_IDS.LEONARD_HEIGHTS.GREY_BUILDING_F1_APT4, MAP_IDS.LEONARD_HEIGHTS.GREY_BUILDING_F1_APT4_TOILET, DOOR_IDS.GREY_BUILDING_F1_APT4_TOILET ),
            [DOOR_IDS.GREY_BUILDING_F1_APT4_BEDROOM]: createDoorEventChain( MAP_IDS.LEONARD_HEIGHTS.GREY_BUILDING_F1_APT4, MAP_IDS.LEONARD_HEIGHTS.GREY_BUILDING_F1_APT4_BEDROOM, DOOR_IDS.GREY_BUILDING_F1_APT4_BEDROOM ),
            //#endregion
        [DOOR_IDS.GREY_BUILDING_F1_APT5]: createDoorEventChain( MAP_IDS.LEONARD_HEIGHTS.GREY_BUILDING_F1_HALL_LEFT, MAP_IDS.LEONARD_HEIGHTS.GREY_BUILDING_F1_APT5, DOOR_IDS.GREY_BUILDING_F1_APT5 ),
            //#region Grey building F1 APT5
            [DOOR_IDS.GREY_BUILDING_F1_APT5_TOILET]: createDoorEventChain( MAP_IDS.LEONARD_HEIGHTS.GREY_BUILDING_F1_APT5, MAP_IDS.LEONARD_HEIGHTS.GREY_BUILDING_F1_APT5_TOILET, DOOR_IDS.GREY_BUILDING_F1_APT5_TOILET ),
            [DOOR_IDS.GREY_BUILDING_F1_APT5_BEDROOM]: createDoorEventChain( MAP_IDS.LEONARD_HEIGHTS.GREY_BUILDING_F1_APT5, MAP_IDS.LEONARD_HEIGHTS.GREY_BUILDING_F1_APT5_BEDROOM, DOOR_IDS.GREY_BUILDING_F1_APT5_BEDROOM ),
            //#endregion
        [DOOR_IDS.GREY_BUILDING_F1_APT6]: createDoorEventChain( MAP_IDS.LEONARD_HEIGHTS.GREY_BUILDING_F1_HALL_LEFT, MAP_IDS.LEONARD_HEIGHTS.GREY_BUILDING_F1_APT6, DOOR_IDS.GREY_BUILDING_F1_APT6 ),
            //#region Grey building F1 APT6
            [DOOR_IDS.GREY_BUILDING_F1_APT6_TOILET]: createDoorEventChain( MAP_IDS.LEONARD_HEIGHTS.GREY_BUILDING_F1_APT6, MAP_IDS.LEONARD_HEIGHTS.GREY_BUILDING_F1_APT6_TOILET, DOOR_IDS.GREY_BUILDING_F1_APT6_TOILET ),
            [DOOR_IDS.GREY_BUILDING_F1_APT6_BEDROOM]: createDoorEventChain( MAP_IDS.LEONARD_HEIGHTS.GREY_BUILDING_F1_APT6, MAP_IDS.LEONARD_HEIGHTS.GREY_BUILDING_F1_APT6_BEDROOM, DOOR_IDS.GREY_BUILDING_F1_APT6_BEDROOM ),
            //#endregion
        //#endregion
        //#region Grey building F2
        [DOOR_IDS.GREY_BUILDING_F2_LEFT_HALL]: createDoorEventChain( MAP_IDS.LEONARD_HEIGHTS.GREY_BUILDING_F2_LOBBY, MAP_IDS.LEONARD_HEIGHTS.GREY_BUILDING_F2_HALL_LEFT, DOOR_IDS.GREY_BUILDING_F2_LEFT_HALL ),
        [DOOR_IDS.GREY_BUILDING_F2_APT1]: createDoorEventChain( MAP_IDS.LEONARD_HEIGHTS.GREY_BUILDING_F2_HALL_LEFT, MAP_IDS.LEONARD_HEIGHTS.GREY_BUILDING_F2_APT1, DOOR_IDS.GREY_BUILDING_F2_APT1 ),
            //#region Grey building F2 APT1
            [DOOR_IDS.GREY_BUILDING_F2_APT1_TOILET]: createDoorEventChain( MAP_IDS.LEONARD_HEIGHTS.GREY_BUILDING_F2_APT1, MAP_IDS.LEONARD_HEIGHTS.GREY_BUILDING_F2_APT1_TOILET, DOOR_IDS.GREY_BUILDING_F2_APT1_TOILET ),
            [DOOR_IDS.GREY_BUILDING_F2_APT1_BEDROOM]: createDoorEventChain( MAP_IDS.LEONARD_HEIGHTS.GREY_BUILDING_F2_APT1, MAP_IDS.LEONARD_HEIGHTS.GREY_BUILDING_F2_APT1_BEDROOM, DOOR_IDS.GREY_BUILDING_F2_APT1_BEDROOM ),
            //#endregion
        [DOOR_IDS.GREY_BUILDING_F2_APT2]: createDoorEventChain( MAP_IDS.LEONARD_HEIGHTS.GREY_BUILDING_F2_HALL_LEFT, MAP_IDS.LEONARD_HEIGHTS.GREY_BUILDING_F2_APT2, DOOR_IDS.GREY_BUILDING_F2_APT2 ),
            //#region Grey building F2 APT2
            [DOOR_IDS.GREY_BUILDING_F2_APT2_TOILET]: createDoorEventChain( MAP_IDS.LEONARD_HEIGHTS.GREY_BUILDING_F2_APT2, MAP_IDS.LEONARD_HEIGHTS.GREY_BUILDING_F2_APT2_TOILET, DOOR_IDS.GREY_BUILDING_F2_APT2_TOILET ),
            [DOOR_IDS.GREY_BUILDING_F2_APT2_BEDROOM]: createDoorEventChain( MAP_IDS.LEONARD_HEIGHTS.GREY_BUILDING_F2_APT2, MAP_IDS.LEONARD_HEIGHTS.GREY_BUILDING_F2_APT2_BEDROOM, DOOR_IDS.GREY_BUILDING_F2_APT2_BEDROOM ),
            //#endregion
        [DOOR_IDS.GREY_BUILDING_F2_APT3]: createDoorEventChain( MAP_IDS.LEONARD_HEIGHTS.GREY_BUILDING_F2_HALL_LEFT, MAP_IDS.LEONARD_HEIGHTS.GREY_BUILDING_F2_APT3, DOOR_IDS.GREY_BUILDING_F2_APT3 ),
            //#region Grey building F2 APT3
            [DOOR_IDS.GREY_BUILDING_F2_APT3_TOILET]: createDoorEventChain( MAP_IDS.LEONARD_HEIGHTS.GREY_BUILDING_F2_APT3, MAP_IDS.LEONARD_HEIGHTS.GREY_BUILDING_F2_APT3_TOILET, DOOR_IDS.GREY_BUILDING_F2_APT3_TOILET ),
            [DOOR_IDS.GREY_BUILDING_F2_APT3_BEDROOM]: createDoorEventChain( MAP_IDS.LEONARD_HEIGHTS.GREY_BUILDING_F2_APT3, MAP_IDS.LEONARD_HEIGHTS.GREY_BUILDING_F2_APT3_BEDROOM, DOOR_IDS.GREY_BUILDING_F2_APT3_BEDROOM ),
            //#endregion
        //#endregion
        //#region Grey building F3
        [DOOR_IDS.GREY_BUILDING_F3_LEFT_HALL]: createDoorEventChain( MAP_IDS.LEONARD_HEIGHTS.GREY_BUILDING_F3_LOBBY, MAP_IDS.LEONARD_HEIGHTS.GREY_BUILDING_F3_HALL_LEFT, DOOR_IDS.GREY_BUILDING_F3_LEFT_HALL ),
        [DOOR_IDS.GREY_BUILDING_F3_APT1]: createDoorEventChain( MAP_IDS.LEONARD_HEIGHTS.GREY_BUILDING_F3_HALL_LEFT, MAP_IDS.LEONARD_HEIGHTS.GREY_BUILDING_F3_APT1, DOOR_IDS.GREY_BUILDING_F3_APT1 ),
            //#region Grey building F3 APT1
            [DOOR_IDS.GREY_BUILDING_F3_APT1_TOILET]: createDoorEventChain( MAP_IDS.LEONARD_HEIGHTS.GREY_BUILDING_F3_APT1, MAP_IDS.LEONARD_HEIGHTS.GREY_BUILDING_F3_APT1_TOILET, DOOR_IDS.GREY_BUILDING_F3_APT1_TOILET ),
            [DOOR_IDS.GREY_BUILDING_F3_APT1_BEDROOM]: createDoorEventChain( MAP_IDS.LEONARD_HEIGHTS.GREY_BUILDING_F3_APT1, MAP_IDS.LEONARD_HEIGHTS.GREY_BUILDING_F3_APT1_BEDROOM, DOOR_IDS.GREY_BUILDING_F3_APT1_BEDROOM ),
            //#endregion
        [DOOR_IDS.GREY_BUILDING_F3_APT2]: createDoorEventChain( MAP_IDS.LEONARD_HEIGHTS.GREY_BUILDING_F3_HALL_LEFT, MAP_IDS.LEONARD_HEIGHTS.GREY_BUILDING_F3_APT2, DOOR_IDS.GREY_BUILDING_F3_APT2 ),
            //#region Grey building F3 APT2
            [DOOR_IDS.GREY_BUILDING_F3_APT2_TOILET]: createDoorEventChain( MAP_IDS.LEONARD_HEIGHTS.GREY_BUILDING_F3_APT2, MAP_IDS.LEONARD_HEIGHTS.GREY_BUILDING_F3_APT2_TOILET, DOOR_IDS.GREY_BUILDING_F3_APT2_TOILET ),
            [DOOR_IDS.GREY_BUILDING_F3_APT2_BEDROOM]: createDoorEventChain( MAP_IDS.LEONARD_HEIGHTS.GREY_BUILDING_F3_APT2, MAP_IDS.LEONARD_HEIGHTS.GREY_BUILDING_F3_APT2_BEDROOM, DOOR_IDS.GREY_BUILDING_F3_APT2_BEDROOM ),
            //#endregion
        [DOOR_IDS.GREY_BUILDING_F3_APT3]: createDoorEventChain( MAP_IDS.LEONARD_HEIGHTS.GREY_BUILDING_F3_HALL_LEFT, MAP_IDS.LEONARD_HEIGHTS.GREY_BUILDING_F3_APT3, DOOR_IDS.GREY_BUILDING_F3_APT3 ),
            //#region Grey building F3 APT3
            [DOOR_IDS.GREY_BUILDING_F3_APT3_TOILET]: createDoorEventChain( MAP_IDS.LEONARD_HEIGHTS.GREY_BUILDING_F3_APT3, MAP_IDS.LEONARD_HEIGHTS.GREY_BUILDING_F3_APT3_TOILET, DOOR_IDS.GREY_BUILDING_F3_APT3_TOILET ),
            [DOOR_IDS.GREY_BUILDING_F3_APT3_BEDROOM]: createDoorEventChain( MAP_IDS.LEONARD_HEIGHTS.GREY_BUILDING_F3_APT3, MAP_IDS.LEONARD_HEIGHTS.GREY_BUILDING_F3_APT3_BEDROOM, DOOR_IDS.GREY_BUILDING_F3_APT3_BEDROOM ),
            //#endregion
        [DOOR_IDS.GREY_BUILDING_F3_RIGHT_HALL]: createDoorEventChain( MAP_IDS.LEONARD_HEIGHTS.GREY_BUILDING_F3_LOBBY, MAP_IDS.LEONARD_HEIGHTS.GREY_BUILDING_F3_HALL_RIGHT, DOOR_IDS.GREY_BUILDING_F3_RIGHT_HALL ),
        [DOOR_IDS.GREY_BUILDING_F3_APT4]: createDoorEventChain( MAP_IDS.LEONARD_HEIGHTS.GREY_BUILDING_F3_HALL_LEFT, MAP_IDS.LEONARD_HEIGHTS.GREY_BUILDING_F3_APT4, DOOR_IDS.GREY_BUILDING_F3_APT4 ),
            //#region Grey building F3 APT4
            [DOOR_IDS.GREY_BUILDING_F3_APT4_TOILET]: createDoorEventChain( MAP_IDS.LEONARD_HEIGHTS.GREY_BUILDING_F3_APT4, MAP_IDS.LEONARD_HEIGHTS.GREY_BUILDING_F3_APT4_TOILET, DOOR_IDS.GREY_BUILDING_F3_APT4_TOILET ),
            [DOOR_IDS.GREY_BUILDING_F3_APT4_BEDROOM]: createDoorEventChain( MAP_IDS.LEONARD_HEIGHTS.GREY_BUILDING_F3_APT4, MAP_IDS.LEONARD_HEIGHTS.GREY_BUILDING_F3_APT4_BEDROOM, DOOR_IDS.GREY_BUILDING_F3_APT4_BEDROOM ),
            //#endregion
        [DOOR_IDS.GREY_BUILDING_F3_APT5]: createDoorEventChain( MAP_IDS.LEONARD_HEIGHTS.GREY_BUILDING_F3_HALL_LEFT, MAP_IDS.LEONARD_HEIGHTS.GREY_BUILDING_F3_APT5, DOOR_IDS.GREY_BUILDING_F3_APT5 ),
            //#region Grey building F3 APT5
            [DOOR_IDS.GREY_BUILDING_F3_APT5_TOILET]: createDoorEventChain( MAP_IDS.LEONARD_HEIGHTS.GREY_BUILDING_F3_APT5, MAP_IDS.LEONARD_HEIGHTS.GREY_BUILDING_F3_APT5_TOILET, DOOR_IDS.GREY_BUILDING_F3_APT5_TOILET ),
            [DOOR_IDS.GREY_BUILDING_F3_APT5_BEDROOM]: createDoorEventChain( MAP_IDS.LEONARD_HEIGHTS.GREY_BUILDING_F3_APT5, MAP_IDS.LEONARD_HEIGHTS.GREY_BUILDING_F3_APT5_BEDROOM, DOOR_IDS.GREY_BUILDING_F3_APT5_BEDROOM ),
            //#endregion
        [DOOR_IDS.GREY_BUILDING_F3_APT6]: createDoorEventChain( MAP_IDS.LEONARD_HEIGHTS.GREY_BUILDING_F3_HALL_LEFT, MAP_IDS.LEONARD_HEIGHTS.GREY_BUILDING_F3_APT6, DOOR_IDS.GREY_BUILDING_F3_APT6 ),
            //#region Grey building F3 APT6
            [DOOR_IDS.GREY_BUILDING_F3_APT6_TOILET]: createDoorEventChain( MAP_IDS.LEONARD_HEIGHTS.GREY_BUILDING_F3_APT6, MAP_IDS.LEONARD_HEIGHTS.GREY_BUILDING_F3_APT6_TOILET, DOOR_IDS.GREY_BUILDING_F3_APT6_TOILET ),
            [DOOR_IDS.GREY_BUILDING_F3_APT6_BEDROOM]: createDoorEventChain( MAP_IDS.LEONARD_HEIGHTS.GREY_BUILDING_F3_APT6, MAP_IDS.LEONARD_HEIGHTS.GREY_BUILDING_F3_APT6_BEDROOM, DOOR_IDS.GREY_BUILDING_F3_APT6_BEDROOM ),
            //#endregion
        //#endregion
    //#endregion
}