type DoorIds = {
    TWO_TOWERS_MAIN_DOOR: string;

    CLUBSHELTER_MAIN_FRONT_DOOR: string;
    CLUBSHELTER_MAIN_INNER_DOOR: string;
    CLUBSHELTER_TOILET_DOOR: string;

    BAKER_STREET_12_FRONT_DOOR: string;
    BAKER_STREET_12_STAIRS_GF: string;
    BAKER_STREET_12_APT_F1: string;
    BAKER_STREET_12_STAIRS_F1: string;
    BAKER_STREET_12_APT_F2: string;
    BAKER_STREET_12_STAIRS_F2: string;
    BAKER_STREET_12_APT_F3: string;
    BAKER_STREET_12_STAIRS_F3: string;
    BAKER_STREET_12_APT_F4: string;

    CAR_SHACK_FRONT_DOOR: string;

    YUM_MART_FRONT_DOOR: string;
    YUM_MART_DOOR_1: string;

    SARDINE_STUDIOS_FRONT_DOOR: string;
    SARDINE_STUDIOS_DOOR_STAIRS_F1: string;
    SARDINE_STUDIOS_DOOR_STAIRS_F2: string;
    SARDINE_STUDIOS_DOOR_STAIRS_TOP: string;
    SARDINE_STUDIOS_COMMON_AREA: string;
    SARDINE_STUDIOS_DOOR_F1_HALL: string;
    SARDINE_STUDIOS_DOOR_F1_APP1: string;
    SARDINE_STUDIOS_DOOR_F1_APP2: string;
    SARDINE_STUDIOS_DOOR_F1_APP3: string;

    GREY_BUILDING_FRONT_DOOR: string;
    GREY_BUILDING_GF_LEFT_HALL: string;
    GREY_BUILDING_GF_RIGHT_HALL: string;
    GREY_BUILDING_GF_APT1: string;
    GREY_BUILDING_GF_APT2: string;
    GREY_BUILDING_GF_APT3: string;
    GREY_BUILDING_GF_APT4: string;
    GREY_BUILDING_GF_APT5: string;
    GREY_BUILDING_GF_APT6: string;
    GREY_BUILDING_GF_APT1_TOILET: string;
    GREY_BUILDING_GF_APT1_BEDROOM: string;
    GREY_BUILDING_GF_APT2_TOILET: string;
    GREY_BUILDING_GF_APT2_BEDROOM: string;
    GREY_BUILDING_GF_APT3_TOILET: string;
    GREY_BUILDING_GF_APT3_BEDROOM: string;
    GREY_BUILDING_GF_APT4_TOILET: string;
    GREY_BUILDING_GF_APT4_BEDROOM: string;
    GREY_BUILDING_GF_APT5_TOILET: string;
    GREY_BUILDING_GF_APT5_BEDROOM: string;
    GREY_BUILDING_GF_APT6_TOILET: string;
    GREY_BUILDING_GF_APT6_BEDROOM: string;
    GREY_BUILDING_F1_LEFT_HALL: string;
    GREY_BUILDING_F1_RIGHT_HALL: string;
    GREY_BUILDING_F1_APT1: string;
    GREY_BUILDING_F1_APT2: string;
    GREY_BUILDING_F1_APT3: string;
    GREY_BUILDING_F1_APT4: string;
    GREY_BUILDING_F1_APT5: string;
    GREY_BUILDING_F1_APT6: string;
    GREY_BUILDING_F1_APT1_TOILET: string;
    GREY_BUILDING_F1_APT1_BEDROOM: string;
    GREY_BUILDING_F1_APT2_TOILET: string;
    GREY_BUILDING_F1_APT2_BEDROOM: string;
    GREY_BUILDING_F1_APT3_TOILET: string;
    GREY_BUILDING_F1_APT3_BEDROOM: string;
    GREY_BUILDING_F1_APT4_TOILET: string;
    GREY_BUILDING_F1_APT4_BEDROOM: string;
    GREY_BUILDING_F1_APT5_TOILET: string;
    GREY_BUILDING_F1_APT5_BEDROOM: string;
    GREY_BUILDING_F1_APT6_TOILET: string;
    GREY_BUILDING_F1_APT6_BEDROOM: string;
    GREY_BUILDING_F2_LEFT_HALL: string;
    GREY_BUILDING_F2_RIGHT_HALL: string;
    GREY_BUILDING_F2_APT1: string;
    GREY_BUILDING_F2_APT2: string;
    GREY_BUILDING_F2_APT3: string;
    GREY_BUILDING_F2_APT1_TOILET: string;
    GREY_BUILDING_F2_APT1_BEDROOM: string;
    GREY_BUILDING_F2_APT2_TOILET: string;
    GREY_BUILDING_F2_APT2_BEDROOM: string;
    GREY_BUILDING_F2_APT3_TOILET: string;
    GREY_BUILDING_F2_APT3_BEDROOM: string;
    GREY_BUILDING_F3_LEFT_HALL: string;
    GREY_BUILDING_F3_RIGHT_HALL: string;
    GREY_BUILDING_F3_APT1: string;
    GREY_BUILDING_F3_APT2: string;
    GREY_BUILDING_F3_APT3: string;
    GREY_BUILDING_F3_APT4: string;
    GREY_BUILDING_F3_APT5: string;
    GREY_BUILDING_F3_APT6: string;
    GREY_BUILDING_F3_APT1_TOILET: string;
    GREY_BUILDING_F3_APT1_BEDROOM: string;
    GREY_BUILDING_F3_APT2_TOILET: string;
    GREY_BUILDING_F3_APT2_BEDROOM: string;
    GREY_BUILDING_F3_APT3_TOILET: string;
    GREY_BUILDING_F3_APT3_BEDROOM: string;
    GREY_BUILDING_F3_APT4_TOILET: string;
    GREY_BUILDING_F3_APT4_BEDROOM: string;
    GREY_BUILDING_F3_APT5_TOILET: string;
    GREY_BUILDING_F3_APT5_BEDROOM: string;
    GREY_BUILDING_F3_APT6_TOILET: string;
    GREY_BUILDING_F3_APT6_BEDROOM: string;
}

export const DOOR_IDS: DoorIds = {
    //#region A3 door event keys
    TWO_TOWERS_MAIN_DOOR: "TWO_TOWERS_MAIN_DOOR",
    //#endregion
    //#region B4 door event keys
    CLUBSHELTER_MAIN_FRONT_DOOR: "DOORKEY_B4_1",
    CLUBSHELTER_MAIN_INNER_DOOR: "DOORKEY_B4_2",
    CLUBSHELTER_TOILET_DOOR: "DOORKEY_B4_3",
    //#endregion
    //#region C2 door event keys
    BAKER_STREET_12_FRONT_DOOR: "DOORKEY_BAKER_STREET_12_FRONT_DOOR",
    BAKER_STREET_12_STAIRS_GF: "DOORKEY_BAKER_STREET_12_STAIRS_GF",
    BAKER_STREET_12_APT_F1: "DOORKEY_BAKER_STREET_12_APT_F1",
    BAKER_STREET_12_STAIRS_F1: "DOORKEY_BAKER_STREET_12_STAIRS_F1",
    BAKER_STREET_12_APT_F2: "DOORKEY_BAKER_STREET_12_APT_F2",
    BAKER_STREET_12_STAIRS_F2: "DOORKEY_BAKER_STREET_12_STAIRS_F2",
    BAKER_STREET_12_APT_F3: "DOORKEY_BAKER_STREET_12_APT_F3",
    BAKER_STREET_12_STAIRS_F3: "DOORKEY_BAKER_STREET_12_STAIRS_F3",
    BAKER_STREET_12_APT_F4: "DOORKEY_BAKER_STREET_12_APT_F4",
    //#endregion
    //#region C3 door event keys
    CAR_SHACK_FRONT_DOOR: "DOORKEY_C3_1",
    //#endregion
    //#region C4 door event keys
    YUM_MART_FRONT_DOOR: "DOORKEY_C4_1",
    YUM_MART_DOOR_1: "DOORKEY_C4_2",
    //#endregion
    //#region D2 door event keys
    SARDINE_STUDIOS_FRONT_DOOR: "DOORKEY_D2_1",
    SARDINE_STUDIOS_DOOR_STAIRS_F1: "DOORKEY_D2_2",
    SARDINE_STUDIOS_DOOR_STAIRS_F2: "DOORKEY_D2_3",
    SARDINE_STUDIOS_DOOR_STAIRS_TOP: "DOORKEY_D2_4",
    SARDINE_STUDIOS_COMMON_AREA: "DOORKEY_D2_5",
    SARDINE_STUDIOS_DOOR_F1_HALL: "DOORKEY_D2_6",
    SARDINE_STUDIOS_DOOR_F1_APP1: "DOORKEY_D2_7",
    SARDINE_STUDIOS_DOOR_F1_APP2: "DOORKEY_D2_8",
    SARDINE_STUDIOS_DOOR_F1_APP3: "DOORKEY_D2_9",
    //#endregion
    //#region E3 door event keys
    GREY_BUILDING_FRONT_DOOR: "DOORKEY_GREY_BUILDING_FRONT_DOOR",
        //#region Grey building GF
        GREY_BUILDING_GF_LEFT_HALL: "DOORKEY_GREY_BUILDING_GF_LOBBY_LEFT_HALL",
        GREY_BUILDING_GF_RIGHT_HALL: "DOORKEY_GREY_BUILDING_GF_LOBBY_RIGHT_HALL",

        GREY_BUILDING_GF_APT1: "DOORKEY_GREY_BUILDING_GF_APT1",
        GREY_BUILDING_GF_APT2: "DOORKEY_GREY_BUILDING_GF_APT2",
        GREY_BUILDING_GF_APT3: "DOORKEY_GREY_BUILDING_GF_APT3",
        GREY_BUILDING_GF_APT4: "DOORKEY_GREY_BUILDING_GF_APT4",
        GREY_BUILDING_GF_APT5: "DOORKEY_GREY_BUILDING_GF_APT5",
        GREY_BUILDING_GF_APT6: "DOORKEY_GREY_BUILDING_GF_APT6",

        GREY_BUILDING_GF_APT1_TOILET: "DOORKEY_GREY_BUILDING_GF_APT1_TOILET",
        GREY_BUILDING_GF_APT1_BEDROOM: "DOORKEY_GREY_BUILDING_GF_APT1_BEDROOM",

        GREY_BUILDING_GF_APT2_TOILET: "DOORKEY_GREY_BUILDING_GF_APT2_TOILET",
        GREY_BUILDING_GF_APT2_BEDROOM: "DOORKEY_GREY_BUILDING_GF_APT2_BEDROOM",

        GREY_BUILDING_GF_APT3_TOILET: "DOORKEY_GREY_BUILDING_GF_APT3_TOILET",
        GREY_BUILDING_GF_APT3_BEDROOM: "DOORKEY_GREY_BUILDING_GF_APT3_BEDROOM",

        GREY_BUILDING_GF_APT4_TOILET: "DOORKEY_GREY_BUILDING_GF_APT4_TOILET",
        GREY_BUILDING_GF_APT4_BEDROOM: "DOORKEY_GREY_BUILDING_GF_APT4_BEDROOM",

        GREY_BUILDING_GF_APT5_TOILET: "DOORKEY_GREY_BUILDING_GF_APT5_TOILET",
        GREY_BUILDING_GF_APT5_BEDROOM: "DOORKEY_GREY_BUILDING_GF_APT5_BEDROOM",

        GREY_BUILDING_GF_APT6_TOILET: "DOORKEY_GREY_BUILDING_GF_APT6_TOILET",
        GREY_BUILDING_GF_APT6_BEDROOM: "DOORKEY_GREY_BUILDING_GF_APT6_BEDROOM",
        //#endregion
        //#region Grey building F1
        GREY_BUILDING_F1_LEFT_HALL: "DOORKEY_GREY_BUILDING_F1_LOBBY_LEFT_HALL",
        GREY_BUILDING_F1_RIGHT_HALL: "DOORKEY_GREY_BUILDING_F1_LOBBY_RIGHT_HALL",

        GREY_BUILDING_F1_APT1: "DOORKEY_GREY_BUILDING_F1_APT1",
        GREY_BUILDING_F1_APT2: "DOORKEY_GREY_BUILDING_F1_APT2",
        GREY_BUILDING_F1_APT3: "DOORKEY_GREY_BUILDING_F1_APT3",
        GREY_BUILDING_F1_APT4: "DOORKEY_GREY_BUILDING_F1_APT4",
        GREY_BUILDING_F1_APT5: "DOORKEY_GREY_BUILDING_F1_APT5",
        GREY_BUILDING_F1_APT6: "DOORKEY_GREY_BUILDING_F1_APT6",

        GREY_BUILDING_F1_APT1_TOILET: "DOORKEY_GREY_BUILDING_F1_APT1_TOILET",
        GREY_BUILDING_F1_APT1_BEDROOM: "DOORKEY_GREY_BUILDING_F1_APT1_BEDROOM",

        GREY_BUILDING_F1_APT2_TOILET: "DOORKEY_GREY_BUILDING_F1_APT2_TOILET",
        GREY_BUILDING_F1_APT2_BEDROOM: "DOORKEY_GREY_BUILDING_F1_APT2_BEDROOM",

        GREY_BUILDING_F1_APT3_TOILET: "DOORKEY_GREY_BUILDING_F1_APT3_TOILET",
        GREY_BUILDING_F1_APT3_BEDROOM: "DOORKEY_GREY_BUILDING_F1_APT3_BEDROOM",

        GREY_BUILDING_F1_APT4_TOILET: "DOORKEY_GREY_BUILDING_F1_APT4_TOILET",
        GREY_BUILDING_F1_APT4_BEDROOM: "DOORKEY_GREY_BUILDING_F1_APT4_BEDROOM",

        GREY_BUILDING_F1_APT5_TOILET: "DOORKEY_GREY_BUILDING_F1_APT5_TOILET",
        GREY_BUILDING_F1_APT5_BEDROOM: "DOORKEY_GREY_BUILDING_F1_APT5_BEDROOM",

        GREY_BUILDING_F1_APT6_TOILET: "DOORKEY_GREY_BUILDING_F1_APT6_TOILET",
        GREY_BUILDING_F1_APT6_BEDROOM: "DOORKEY_GREY_BUILDING_F1_APT6_BEDROOM",
        //#endregion
        //#region Grey building F2
        GREY_BUILDING_F2_LEFT_HALL: "DOORKEY_GREY_BUILDING_F2_LOBBY_LEFT_HALL",
        GREY_BUILDING_F2_RIGHT_HALL: "DOORKEY_GREY_BUILDING_F2_LOBBY_LEFT_HALL",

        GREY_BUILDING_F2_APT1: "DOORKEY_GREY_BUILDING_F2_APT1",
        GREY_BUILDING_F2_APT2: "DOORKEY_GREY_BUILDING_F2_APT2",
        GREY_BUILDING_F2_APT3: "DOORKEY_GREY_BUILDING_F2_APT3",

        GREY_BUILDING_F2_APT1_TOILET: "DOORKEY_GREY_BUILDING_F2_APT1_TOILET",
        GREY_BUILDING_F2_APT1_BEDROOM: "DOORKEY_GREY_BUILDING_F2_APT1_BEDROOM",

        GREY_BUILDING_F2_APT2_TOILET: "DOORKEY_GREY_BUILDING_F2_APT2_TOILET",
        GREY_BUILDING_F2_APT2_BEDROOM: "DOORKEY_GREY_BUILDING_F2_APT2_BEDROOM",

        GREY_BUILDING_F2_APT3_TOILET: "DOORKEY_GREY_BUILDING_F2_APT3_TOILET",
        GREY_BUILDING_F2_APT3_BEDROOM: "DOORKEY_GREY_BUILDING_F2_APT3_BEDROOM",
        //#endregion
        //#region Grey building F3
        GREY_BUILDING_F3_LEFT_HALL: "DOORKEY_GREY_BUILDING_F3_LOBBY_LEFT_HALL",
        GREY_BUILDING_F3_RIGHT_HALL: "DOORKEY_GREY_BUILDING_F3_LOBBY_RIGHT_HALL",

        GREY_BUILDING_F3_APT1: "DOORKEY_GREY_BUILDING_F3_APT1",
        GREY_BUILDING_F3_APT2: "DOORKEY_GREY_BUILDING_F3_APT2",
        GREY_BUILDING_F3_APT3: "DOORKEY_GREY_BUILDING_F3_APT3",
        GREY_BUILDING_F3_APT4: "DOORKEY_GREY_BUILDING_F3_APT4",
        GREY_BUILDING_F3_APT5: "DOORKEY_GREY_BUILDING_F3_APT5",
        GREY_BUILDING_F3_APT6: "DOORKEY_GREY_BUILDING_F3_APT6",

        GREY_BUILDING_F3_APT1_TOILET: "DOORKEY_GREY_BUILDING_F3_APT1_TOILET",
        GREY_BUILDING_F3_APT1_BEDROOM: "DOORKEY_GREY_BUILDING_F3_APT1_BEDROOM",

        GREY_BUILDING_F3_APT2_TOILET: "DOORKEY_GREY_BUILDING_F3_APT2_TOILET",
        GREY_BUILDING_F3_APT2_BEDROOM: "DOORKEY_GREY_BUILDING_F3_APT2_BEDROOM",

        GREY_BUILDING_F3_APT3_TOILET: "DOORKEY_GREY_BUILDING_F3_APT3_TOILET",
        GREY_BUILDING_F3_APT3_BEDROOM: "DOORKEY_GREY_BUILDING_F3_APT3_BEDROOM",

        GREY_BUILDING_F3_APT4_TOILET: "DOORKEY_GREY_BUILDING_F3_APT4_TOILET",
        GREY_BUILDING_F3_APT4_BEDROOM: "DOORKEY_GREY_BUILDING_F3_APT4_BEDROOM",

        GREY_BUILDING_F3_APT5_TOILET: "DOORKEY_GREY_BUILDING_F3_APT5_TOILET",
        GREY_BUILDING_F3_APT5_BEDROOM: "DOORKEY_GREY_BUILDING_F3_APT5_BEDROOM",

        GREY_BUILDING_F3_APT6_TOILET: "DOORKEY_GREY_BUILDING_F3_APT6_TOILET",
        GREY_BUILDING_F3_APT6_BEDROOM: "DOORKEY_GREY_BUILDING_F3_APT6_BEDROOM",
        //#endregion
    //#endregion
}