export const DOORKEY_SARDINE_STUDIOS_FRONT_DOOR = "DOORKEY_D2_1";
export const DOORKEY_SARDINE_STUDIOS_DOOR_STAIRS_F1 = "DOORKEY_D2_2";
export const DOORKEY_SARDINE_STUDIOS_DOOR_F1_HALL = "DOORKEY_D2_6";
export const DOORKEY_SARDINE_STUDIOS_DOOR_F1_APP1 = "DOORKEY_D2_7";
export const DOORKEY_SARDINE_STUDIOS_DOOR_F1_APP2 = "DOORKEY_D2_8";
export const DOORKEY_SARDINE_STUDIOS_DOOR_F1_APP3 = "DOORKEY_D2_9";

export const DOORKEY_SARDINE_STUDIOS_DOOR_STAIRS_F2 = "DOORKEY_D2_3";
export const DOORKEY_SARDINE_STUDIOS_DOOR_STAIRS_TOP = "DOORKEY_D2_4";
export const DOORKEY_SARDINE_STUDIOS_COMMON_AREA = "DOORKEY_D2_5";