const { 
    ATT_HEALTH_POINTS, ATT_POWER_POINTS, ATT_PH_ATTACK, ATT_PH_DEFENSE,
    ATT_SP_ATTACK, ATT_SP_DEFENSE, ATT_SPEED, ATT_LUCK
} = require('../game-data/globals')

const { 
    MOVE_TYPE_HEAL, MOVE_TYPE_STAT_UP, MOVE_TYPE_STAT_DOWN,
    MOVE_TYPE_STAT_EFF, MOVE_TYPE_PH_ATTACK, MOVE_TYPE_SP_ATTACK,

    MOVE_PROP_KEY_NAME, MOVE_PROP_KEY_DESCRIPTION,
    MOVE_PROP_KEY_TYPE, MOVE_PROP_KEY_SUBTYPE,
    MOVE_PROP_KEY_ATTRIBUTE, MOVE_PROP_KEY_BASE_VALUE,
    MOVE_PROP_KEY_PP_COST, MOVE_PROP_KEY_EFFECT_TYPE,
    MOVE_PROP_KEY_TURNS_AMOUNT, MOVE_PROP_KEY_MODIFIER
} = require('../game-data/moveGlobals')

const HEAL_SMALL = {
    [MOVE_PROP_KEY_NAME]: "Minor healing",
    [MOVE_PROP_KEY_DESCRIPTION]: "Heal about 20 points of health on target",
    [MOVE_PROP_KEY_TYPE]: MOVE_TYPE_HEAL,
    [MOVE_PROP_KEY_ATTRIBUTE]: ATT_HEALTH_POINTS,
    [MOVE_PROP_KEY_BASE_VALUE]: 20,
    [MOVE_PROP_KEY_MODIFIER]: .2,
    [MOVE_PROP_KEY_PP_COST]: 5
}
const HEAL_LARGE = {
    [MOVE_PROP_KEY_NAME]: "Minor healing",
    [MOVE_PROP_KEY_DESCRIPTION]: "Heal about 50 points of health on target",
    [MOVE_PROP_KEY_TYPE]: MOVE_TYPE_HEAL,
    [MOVE_PROP_KEY_ATTRIBUTE]: ATT_HEALTH_POINTS,
    [MOVE_PROP_KEY_BASE_VALUE]: 50,
    [MOVE_PROP_KEY_MODIFIER]: .2,
    [MOVE_PROP_KEY_PP_COST]: 12
}
const HEAL_PP = { 
    [MOVE_PROP_KEY_NAME]: "PP restore",
    [MOVE_PROP_KEY_DESCRIPTION]: "Restore about 20 points of power points on target",
    [MOVE_PROP_KEY_TYPE]: MOVE_TYPE_HEAL,
    [MOVE_PROP_KEY_ATTRIBUTE]: ATT_POWER_POINTS,
    [MOVE_PROP_KEY_BASE_VALUE]: 20,
    [MOVE_PROP_KEY_MODIFIER]: .2,
    [MOVE_PROP_KEY_PP_COST]: 10
}
const SMALL_SP_ATTK_UP = {
    [MOVE_PROP_KEY_NAME]: "SP attack up",
    [MOVE_PROP_KEY_DESCRIPTION]: "Temporarily buff special attack of target.",
    [MOVE_PROP_KEY_TYPE]: MOVE_TYPE_STAT_UP,
    [MOVE_PROP_KEY_ATTRIBUTE]: ATT_SP_ATTACK,
    [MOVE_PROP_KEY_BASE_VALUE]: 5,
    [MOVE_PROP_KEY_MODIFIER]: .2,
    [MOVE_PROP_KEY_PP_COST]: 8,
    [MOVE_PROP_KEY_TURNS_AMOUNT]: 3
}
const SMALL_SP_DEF_UP = {
    [MOVE_PROP_KEY_NAME]: "SP def up",
    [MOVE_PROP_KEY_DESCRIPTION]: "Temporarily buff special defense of target.",
    [MOVE_PROP_KEY_TYPE]: MOVE_TYPE_STAT_UP,
    [MOVE_PROP_KEY_ATTRIBUTE]: ATT_SP_DEFENSE,
    [MOVE_PROP_KEY_BASE_VALUE]: 5,
    [MOVE_PROP_KEY_MODIFIER]: .2,
    [MOVE_PROP_KEY_PP_COST]: 8,
    [MOVE_PROP_KEY_TURNS_AMOUNT]: 3
}
const SMALL_PH_ATTK_UP = {
    [MOVE_PROP_KEY_NAME]: "PH attack up",
    [MOVE_PROP_KEY_DESCRIPTION]: "Temporarily buff physical attack of target.",
    [MOVE_PROP_KEY_TYPE]: MOVE_TYPE_STAT_UP,
    [MOVE_PROP_KEY_ATTRIBUTE]: ATT_PH_ATTACK,
    [MOVE_PROP_KEY_BASE_VALUE]: 5,
    [MOVE_PROP_KEY_MODIFIER]: .2,
    [MOVE_PROP_KEY_PP_COST]: 8,
    [MOVE_PROP_KEY_TURNS_AMOUNT]: 3
}
const SMALL_PH_DEF_UP = {
    [MOVE_PROP_KEY_NAME]: "PH defense up",
    [MOVE_PROP_KEY_DESCRIPTION]: "Temporarily buff physical defense of target.",
    [MOVE_PROP_KEY_TYPE]: MOVE_TYPE_STAT_UP,
    [MOVE_PROP_KEY_ATTRIBUTE]: ATT_PH_DEFENSE,
    [MOVE_PROP_KEY_BASE_VALUE]: 5,
    [MOVE_PROP_KEY_MODIFIER]: .2,
    [MOVE_PROP_KEY_PP_COST]: 8,
    [MOVE_PROP_KEY_TURNS_AMOUNT]: 3
}
const SMALL_SPEED_UP = {
    [MOVE_PROP_KEY_NAME]: "Speed up",
    [MOVE_PROP_KEY_DESCRIPTION]: "Temporarily buff speed of target.",
    [MOVE_PROP_KEY_TYPE]: MOVE_TYPE_STAT_UP,
    [MOVE_PROP_KEY_ATTRIBUTE]: ATT_SPEED,
    [MOVE_PROP_KEY_BASE_VALUE]: 5,
    [MOVE_PROP_KEY_MODIFIER]: .2,
    [MOVE_PROP_KEY_PP_COST]: 8,
    [MOVE_PROP_KEY_TURNS_AMOUNT]: 3
}
const SMALL_LUCK_UP = {
    [MOVE_PROP_KEY_NAME]: "Luck up",
    [MOVE_PROP_KEY_DESCRIPTION]: "Temporarily buff luck of target.",
    [MOVE_PROP_KEY_TYPE]: MOVE_TYPE_STAT_UP,
    [MOVE_PROP_KEY_ATTRIBUTE]: ATT_LUCK,
    [MOVE_PROP_KEY_BASE_VALUE]: 5,
    [MOVE_PROP_KEY_MODIFIER]: .2,
    [MOVE_PROP_KEY_PP_COST]: 8,
    [MOVE_PROP_KEY_TURNS_AMOUNT]: 3
}
const SMALL_SP_ATTK_DOWN = {
    [MOVE_PROP_KEY_NAME]: "SP attack down",
    [MOVE_PROP_KEY_DESCRIPTION]: "Temporarily debuff special attack of target.",
    [MOVE_PROP_KEY_TYPE]: MOVE_TYPE_STAT_DOWN,
    [MOVE_PROP_KEY_ATTRIBUTE]: ATT_SP_ATTACK,
    [MOVE_PROP_KEY_BASE_VALUE]: 5,
    [MOVE_PROP_KEY_MODIFIER]: .2,
    [MOVE_PROP_KEY_PP_COST]: 8,
    [MOVE_PROP_KEY_TURNS_AMOUNT]: 3
}
const SMALL_SP_DEF_DOWN = {
    [MOVE_PROP_KEY_NAME]: "SP defense down",
    [MOVE_PROP_KEY_DESCRIPTION]: "Temporarily debuff special defense of target.",
    [MOVE_PROP_KEY_TYPE]: MOVE_TYPE_STAT_DOWN,
    [MOVE_PROP_KEY_ATTRIBUTE]: ATT_SP_DEFENSE,
    [MOVE_PROP_KEY_BASE_VALUE]: 5,
    [MOVE_PROP_KEY_MODIFIER]: .2,
    [MOVE_PROP_KEY_PP_COST]: 8,
    [MOVE_PROP_KEY_TURNS_AMOUNT]: 3
}
const SMALL_PH_ATTK_DOWN = {
    [MOVE_PROP_KEY_NAME]: "PH attack down",
    [MOVE_PROP_KEY_DESCRIPTION]: "Temporarily debuff physical attack of target.",
    [MOVE_PROP_KEY_TYPE]: MOVE_TYPE_STAT_DOWN,
    [MOVE_PROP_KEY_ATTRIBUTE]: ATT_PH_ATTACK,
    [MOVE_PROP_KEY_BASE_VALUE]: 5,
    [MOVE_PROP_KEY_MODIFIER]: .2,
    [MOVE_PROP_KEY_PP_COST]: 8,
    [MOVE_PROP_KEY_TURNS_AMOUNT]: 3
}
const SMALL_PH_DEF_DOWN = {
    [MOVE_PROP_KEY_NAME]: "PH defense down",
    [MOVE_PROP_KEY_DESCRIPTION]: "Temporarily debuff physical defense of target.",
    [MOVE_PROP_KEY_TYPE]: MOVE_TYPE_STAT_DOWN,
    [MOVE_PROP_KEY_ATTRIBUTE]: ATT_PH_DEFENSE,
    [MOVE_PROP_KEY_BASE_VALUE]: 5,
    [MOVE_PROP_KEY_MODIFIER]: .2,
    [MOVE_PROP_KEY_PP_COST]: 8,
    [MOVE_PROP_KEY_TURNS_AMOUNT]: 3
}
const SMALL_SPEED_DOWN = {
    [MOVE_PROP_KEY_NAME]: "Speed down",
    [MOVE_PROP_KEY_DESCRIPTION]: "Temporarily debuff speed of target.",
    [MOVE_PROP_KEY_TYPE]: MOVE_TYPE_STAT_DOWN,
    [MOVE_PROP_KEY_ATTRIBUTE]: ATT_SPEED,
    [MOVE_PROP_KEY_BASE_VALUE]: 5,
    [MOVE_PROP_KEY_MODIFIER]: .2,
    [MOVE_PROP_KEY_PP_COST]: 8,
    [MOVE_PROP_KEY_TURNS_AMOUNT]: 3
}
const SMALL_LUCK_DOWN = {
    [MOVE_PROP_KEY_NAME]: "Luck down",
    [MOVE_PROP_KEY_DESCRIPTION]: "Temporarily debuff luck of target.",
    [MOVE_PROP_KEY_TYPE]: MOVE_TYPE_STAT_DOWN,
    [MOVE_PROP_KEY_ATTRIBUTE]: ATT_LUCK,
    [MOVE_PROP_KEY_BASE_VALUE]: 5,
    [MOVE_PROP_KEY_MODIFIER]: .2,
    [MOVE_PROP_KEY_PP_COST]: 8,
    [MOVE_PROP_KEY_TURNS_AMOUNT]: 3
}
///
const PH_ATTK_1 = {
    [MOVE_PROP_KEY_NAME]: "Ph attack 1",
    [MOVE_PROP_KEY_DESCRIPTION]: "Basic but predictable physical attack.",
    [MOVE_PROP_KEY_TYPE]: MOVE_TYPE_PH_ATTACK,
    [MOVE_PROP_KEY_BASE_VALUE]: 20,
    [MOVE_PROP_KEY_MODIFIER]: .2,
    [MOVE_PROP_KEY_PP_COST]: 2
}
const PH_ATTK_2 = {
    [MOVE_PROP_KEY_NAME]: "Ph attack 2",
    [MOVE_PROP_KEY_DESCRIPTION]: "Strong but unreliable physical attack.",
    [MOVE_PROP_KEY_TYPE]: MOVE_TYPE_PH_ATTACK,
    [MOVE_PROP_KEY_BASE_VALUE]: 30,
    [MOVE_PROP_KEY_MODIFIER]: .5,
    [MOVE_PROP_KEY_PP_COST]: 5
}
const SP_ATTK_1 = {
    [MOVE_PROP_KEY_NAME]: "Special attack 1",
    [MOVE_PROP_KEY_DESCRIPTION]: "Basic but predictable special attack.",
    [MOVE_PROP_KEY_TYPE]: MOVE_TYPE_SP_ATTACK,
    [MOVE_PROP_KEY_BASE_VALUE]: 20,
    [MOVE_PROP_KEY_MODIFIER]: .2,
    [MOVE_PROP_KEY_PP_COST]: 2
}
const SP_ATTK_2 = {
    [MOVE_PROP_KEY_NAME]: "Special attack 2",
    [MOVE_PROP_KEY_DESCRIPTION]: "Strong but unreliable special attack.",
    [MOVE_PROP_KEY_TYPE]: MOVE_TYPE_SP_ATTACK,
    [MOVE_PROP_KEY_BASE_VALUE]: 30,
    [MOVE_PROP_KEY_MODIFIER]: .5,
    [MOVE_PROP_KEY_PP_COST]: 5
}
const STANDARD_ATTACK = {
    [MOVE_PROP_KEY_NAME]: "Standard attack",
    [MOVE_PROP_KEY_DESCRIPTION]: "The most standard punch.",
    [MOVE_PROP_KEY_TYPE]: MOVE_TYPE_PH_ATTACK,
    [MOVE_PROP_KEY_BASE_VALUE]: 10,
    [MOVE_PROP_KEY_MODIFIER]: .2,
    [MOVE_PROP_KEY_PP_COST]: 0,
}
//
module.exports = {
    HEAL_SMALL, HEAL_LARGE, HEAL_PP,
    SMALL_PH_ATTK_UP, SMALL_PH_ATTK_DOWN,
    SMALL_PH_DEF_UP, SMALL_PH_DEF_DOWN, 
    SMALL_SP_ATTK_UP, SMALL_SP_ATTK_DOWN,
    SMALL_SP_DEF_UP, SMALL_SP_DEF_DOWN,
    SMALL_SPEED_UP, SMALL_SPEED_DOWN,
    SMALL_LUCK_UP, SMALL_LUCK_DOWN,
    PH_ATTK_1, PH_ATTK_2,
    SP_ATTK_1, SP_ATTK_2,
    STANDARD_ATTACK
}