const { STRD_SPRITE_HEIGHT, STRD_SPRITE_WIDTH } = require('./globals') 

const BATTLE_SPRITE_WIDTH   = STRD_SPRITE_WIDTH * 1.5;
const BATTLE_SPRITE_HEIGHT  = STRD_SPRITE_HEIGHT * 1.5;

const BATTLE_SPRITE_WIDTH_IN_SHEET = 96;
const BATTLE_SPRITE_HEIGHT_IN_SHEET = 168;

const LEFT_BATTLE_POSITION_1    = { 'column': 4, 'row': 7 };
const LEFT_BATTLE_POSITION_2    = { 'column': 6, 'row': 9 };
const LEFT_BATTLE_POSITION_3    = { 'column': 4, 'row': 11 };

const RIGHT_BATTLE_POSITION_1   = { 'column': 20, 'row': 7 };
const RIGHT_BATTLE_POSITION_2    = { 'column': 18, 'row': 9 };
const RIGHT_BATTLE_POSITION_3    = { 'column': 20, 'row': 11 };

const SHEET_ROW_BATTLE_FACING_LEFT         = 4;
const SHEET_ROW_BATTLE_FACING_RIGHT        = 5;
const SHEET_ROW_BATTLE_FACING_RIGHT        = 6;

const BATTLE_PHASE_BEGIN_TURN   = "PHASE_1";
const BATTLE_PHASE_SELECT_MOVE  = "PHASE_2";
const BATTLE_PHASE_DO_MOVES     = "PHASE_3";
const BATTLE_PHASE_END_TURN     = "PHASE_4";
const BATTLE_PHASE_END_BATTLE   = "PHASE_5";

module.exports = {
    BATTLE_SPRITE_WIDTH,
    BATTLE_SPRITE_HEIGHT,

    LEFT_BATTLE_POSITION_1,
    LEFT_BATTLE_POSITION_2,
    LEFT_BATTLE_POSITION_3,

    RIGHT_BATTLE_POSITION_1,
    RIGHT_BATTLE_POSITION_2,
    RIGHT_BATTLE_POSITION_3,
    
    SHEET_ROW_BATTLE_FACING_LEFT,
    SHEET_ROW_BATTLE_FACING_RIGHT,
    SHEET_ROW_BATTLE_FACING_RIGHT,

    BATTLE_SPRITE_WIDTH_IN_SHEET,
    BATTLE_SPRITE_HEIGHT_IN_SHEET,

    BATTLE_PHASE_BEGIN_TURN,
    BATTLE_PHASE_SELECT_MOVE,
    BATTLE_PHASE_DO_MOVES,
    BATTLE_PHASE_END_TURN,
    BATTLE_PHASE_END_BATTLE
}