const { STRD_SPRITE_HEIGHT, STRD_SPRITE_WIDTH, CANVAS_HEIGHT, CANVAS_WIDTH } = require('./globals') 

const BATTLE_SPRITE_WIDTH   = STRD_SPRITE_WIDTH * 1.5;
const BATTLE_SPRITE_HEIGHT  = STRD_SPRITE_HEIGHT * 1.5;

const BATTLE_SPRITE_WIDTH_IN_SHEET = 96;
const BATTLE_SPRITE_HEIGHT_IN_SHEET = 168;

const LEFT_BATTLE_POSITION_1    = { 'column': 4, 'row': 6 };
const LEFT_BATTLE_POSITION_2    = { 'column': 5, 'row': 9 };
const LEFT_BATTLE_POSITION_3    = { 'column': 4, 'row': 12 };

const RIGHT_BATTLE_POSITION_1   = { 'column': 20, 'row': 6 };
const RIGHT_BATTLE_POSITION_2    = { 'column': 19, 'row': 9 };
const RIGHT_BATTLE_POSITION_3    = { 'column': 20, 'row': 12 };

const SHEET_ROW_BATTLE_FACING_LEFT         = 4;
const SHEET_ROW_BATTLE_FACING_RIGHT        = 5;
const SHEET_ROW_BATTLE_PUNCH        = 6;

const BATTLE_PHASE_BEGIN_TURN   = "PHASE_1";
const BATTLE_PHASE_SELECT_MOVE  = "PHASE_2";
const BATTLE_PHASE_DO_MOVES     = "PHASE_3";
const BATTLE_PHASE_END_TURN     = "PHASE_4";
const BATTLE_PHASE_END_BATTLE   = "PHASE_5";

const BATTLE_STEP_GO_TO = "STEP_GO_TO";
const BATTLE_STEP_GO_BACK = "STEP_GO_BACK";
const BATTLE_STEP_MOVE_FORWARD = "STEP_MOVE_FORWARD";
const BATTLE_STEP_ANIMATION = "STEP_ANIMATION"
const BATTLE_STEP_HIT = "STEP_HIT";

const CONTROL_UP = "CTRL_UP";
const CONTROL_LEFT = "CTRL_LEFT";
const CONTROL_RIGHT = "CTRL_RIGHT";
const CONTROL_DOWN = "CTRL_DOWN";

const TEXTBOX_XY = { "x": CANVAS_WIDTH * .25, "y": (CANVAS_HEIGHT / 6) * 5 }
const TEXTBOX_DIMENSIONS = { "width": CANVAS_WIDTH * .35, "height": CANVAS_HEIGHT / 6}

module.exports = {
    BATTLE_SPRITE_WIDTH,
    BATTLE_SPRITE_HEIGHT,

    LEFT_BATTLE_POSITION_1,
    LEFT_BATTLE_POSITION_2,
    LEFT_BATTLE_POSITION_3,

    RIGHT_BATTLE_POSITION_1,
    RIGHT_BATTLE_POSITION_2,
    RIGHT_BATTLE_POSITION_3,
    
    SHEET_ROW_BATTLE_FACING_LEFT,
    SHEET_ROW_BATTLE_FACING_RIGHT,
    SHEET_ROW_BATTLE_PUNCH,

    BATTLE_SPRITE_WIDTH_IN_SHEET,
    BATTLE_SPRITE_HEIGHT_IN_SHEET,

    BATTLE_PHASE_BEGIN_TURN,
    BATTLE_PHASE_SELECT_MOVE,
    BATTLE_PHASE_DO_MOVES,
    BATTLE_PHASE_END_TURN,
    BATTLE_PHASE_END_BATTLE,

    BATTLE_STEP_GO_TO,
    BATTLE_STEP_GO_BACK,
    BATTLE_STEP_MOVE_FORWARD,
    BATTLE_STEP_ANIMATION,
    BATTLE_STEP_HIT,

    CONTROL_UP,
    CONTROL_LEFT,
    CONTROL_RIGHT,
    CONTROL_DOWN,
    
    TEXTBOX_XY,
    TEXTBOX_DIMENSIONS
}