module.exports = {
    INTERACTION_YES : "YES",
    INTERACTION_NO  : "NO",

    LOGGABLE_INTERACTION_1 : "LI1",
    LOGGABLE_INTERACTION_2 : "LI2",
    LOGGABLE_INTERACTION_3 : "LI3",
    LOGGABLE_INTERACTION_4 : "LI4",
    LOGGABLE_INTERACTION_5 : "LI5",

    PLAYER_NAME: "Player",
    PLAYER_ID: "PLAYER",
    SPEAK_SPEAKER: "Speaker"
}