module.exports = {
    INTERACTION_YES : "YES",
    INTERACTION_NO  : "NO",

    LOGGABLE_INTERACTION_1 : "LI1",
    LOGGABLE_INTERACTION_2 : "LI2",
    LOGGABLE_INTERACTION_3 : "LI3",
    LOGGABLE_INTERACTION_4 : "LI4",
    LOGGABLE_INTERACTION_5 : "LI5",
    LOGGABLE_INTERACTION_6 : "LI6",
    LOGGABLE_INTERACTION_7 : "LI7",
    LOGGABLE_INTERACTION_8 : "LI8",
    LOGGABLE_INTERACTION_9 : "LI9",
    UNLOCK_DOOR_TEST: "UDT",

    PLAYER_NAME: "Julius",
    PLAYER_ID: "PLAYER",
    SPEAK_SPEAKER: "Speaker",
    COLLECTABLE_COIN: "COLL_COIN",
    COLLECTABLE_JUICE_CAN: "COLL_JUICE_CAN"
}