module.exports = {
    MOVE_TYPE_HEAL: "HE",
    MOVE_TYPE_STAT_UP: "SU",
    MOVE_TYPE_STAT_DOW: "SD",
    MOVE_TYPE_STAT_EFF: "SE",
    MOVE_TYPE_PH_ATTACK: "PH",
    MOVE_TYPE_SP_ATTACK: "SH",

    MOVE_PROP_KEY_NAME: "NAME",
    MOVE_PROP_KEY_DESCRIPTION: "DESCRIPTION",
    MOVE_PROP_KEY_TYPE:"TYPE",
    MOVE_PROP_KEY_SUBTYPE: "SUBTYPE",
    MOVE_PROP_KEY_ATTRIBUTE: "ATTRIBUTE",
    MOVE_PROP_KEY_BASE_VALUE: "BASE_VALUE",
    MOVE_PROP_KEY_MODIFIER: "MODIFIER",
    MOVE_PROP_KEY_PP_COST: "PP_COST",
    MOVE_PROP_KEY_EFFECT_TYPE: "EFFECT_TYPE",
    MOVE_PROP_KEY_TURNS_AMOUNT: "TURNS_AMOUNT"    
}

