module.exports = {
    COLOR_BLACK: '#000000',
    COLOR_WHITE: '#ffffff',
    COLOR_PRIMARY: '#9c1e86',
    COLOR_SECONDARY: '#D82BBA',
    COLOR_TERTIARY: '#00384D',
    COLOR_BACKGROUND: '#00384D',

    MENU_TYPE_EQUIP: "EQUIP",
    MENU_TYPE_STATUS: "STATUS",
    MENU_TYPE_BUY: "BUY",
    MENU_TYPE_MAP: "MAP",
    MENU_TYPE_SELL: "SELL",
    MENU_TYPE_GAME: "GAME",
    MENU_TYPE_INVENTORY: "INVENTORY",
    MENU_TYPE_MEMBERS: "MEMBERS",

    MENU_BUTTON_USE: "USE",
    MENU_BUTTON_MOVE: "MOVE",
    MENU_BUTTON_EQUIP: "EQUIP",
    MENU_BUTTON_UNEQUIP: "UNEQUIP",
    MENU_BUTTON_RETURN: "RETURN",
    MENU_BUTTON_DISCARD: "DISCARD",
    MENU_BUTTON_SHOW_STATUS: "SHOW STATUS",
    MENU_BUTTON_SHOW_ON_MAP: "SHOW ON MAP",
    MENU_BUTTON_REMOVE_FROM: "REMOVE FROM LIST",
    MENU_BUTTON_CONFIRM_TRANS: "CONFIRM TRANSACTION",

    MENU_ACTION_NEXT: "NEXT",
    MENU_ACTION_PREVIOUS: "PREVIOUS"
}