const { DISPLAY_MODE_PORTRAIT, GRID_BLOCK_PX } = require('./globals');
const { BUBBLE_TOP, BUBBLE_MIDDLE } = require('./textboxGlobals');

module.exports = {
    COLOR_BLACK: '#000000',
    COLOR_WHITE: '#ffffff',
    COLOR_PRIMARY: '#9c1e86',
    COLOR_SECONDARY: '#D82BBA',
    COLOR_TERTIARY: '#00384D',
    COLOR_BACKGROUND: '#00384D',

    MENU_TYPE_EQUIP: "EQUIP",
    MENU_TYPE_STATUS: "STATUS",
    MENU_TYPE_BUY: "BUY",
    MENU_TYPE_MAP: "MAP",
    MENU_TYPE_SELL: "SELL",
    MENU_TYPE_GAME: "GAME",
    MENU_TYPE_INVENTORY: "INVENTORY",
    MENU_TYPE_MEMBERS: "MEMBERS",

    MENU_BUTTON_USE: "USE",
    MENU_BUTTON_MOVE: "MOVE",
    MENU_BUTTON_EQUIP: "EQUIP",
    MENU_BUTTON_UNEQUIP: "UNEQUIP",
    MENU_BUTTON_RETURN: "RETURN",
    MENU_BUTTON_DISCARD: "DISCARD",
    MENU_BUTTON_SHOW_STATUS: "SHOW STATUS",
    MENU_BUTTON_SHOW_ON_MAP: "SHOW ON MAP",
    MENU_BUTTON_REMOVE_FROM: "REMOVE FROM LIST",
    MENU_BUTTON_CONFIRM_TRANS: "CONFIRM TRANSACTION",

    MENU_ACTION_NEXT: "NEXT",
    MENU_ACTION_PREVIOUS: "PREVIOUS",

    MENU_TAB_PARTY: "MTP",
    MENU_TAB_INVENTORY: "MTI",
    MENU_TAB_MAP: "MTM",
    MENU_TAB_GAME: "MTG",

    MENU_GRID_COLUMNS: DISPLAY_MODE_PORTRAIT ? 8 : 24,
    MENU_GRID_ROWS: DISPLAY_MODE_PORTRAIT ? 8 : 16,

    MENU_WIDTH: DISPLAY_MODE_PORTRAIT ? 8 : 24,
    MENU_HEIGHT: DISPLAY_MODE_PORTRAIT ? 8 : 16,

    MENU_HEADER_HEIGHT: DISPLAY_MODE_PORTRAIT? GRID_BLOCK_PX : GRID_BLOCK_PX * 2,

    MENU_HEADER_ACTIVE_COLUMNS: DISPLAY_MODE_PORTRAIT ? 8 : 12,
    MENU_HEADER_ACTIVE_ROWS: DISPLAY_MODE_PORTRAIT ? 1 : 2,
    MENU_HEADER_ACTIVE_ROWSTYLES: DISPLAY_MODE_PORTRAIT ? [ BUBBLE_TOP ] : [ BUBBLE_TOP, BUBBLE_MIDDLE ],

    MENU_HEADER_INACTIVE_COLUMNS: DISPLAY_MODE_PORTRAIT ? 0 : 4,
    MENU_HEADER_INACTIVE_ROWS: DISPLAY_MODE_PORTRAIT ? 0 : 1,
    MENU_HEADER_INACTIVE_Y: DISPLAY_MODE_PORTRAIT? 0 : GRID_BLOCK_PX,
    MENU_HEADER_INACTIVE_ROWSTYLES: [ BUBBLE_TOP ],

    MENU_MARGIN_SIDES: DISPLAY_MODE_PORTRAIT? GRID_BLOCK_PX / 2 : GRID_BLOCK_PX,
    MENU_MARGIN_TOP_DOWN: DISPLAY_MODE_PORTRAIT? GRID_BLOCK_PX / 4 : GRID_BLOCK_PX / 2,

    MENU_BUTTON_STANDARD_WIDTH: DISPLAY_MODE_PORTRAIT? GRID_BLOCK_PX * 7 : GRID_BLOCK_PX * 10,
    MENU_BUTTON_STANDARD_HEIGHT: DISPLAY_MODE_PORTRAIT? GRID_BLOCK_PX * 1 : GRID_BLOCK_PX * 1.5, 

    MENU_TEXTBOX_ROWS: DISPLAY_MODE_PORTRAIT? GRID_BLOCK_PX * 2 : GRID_BLOCK_PX * 3,
    MENU_TEXTBOX_Y: DISPLAY_MODE_PORTRAIT ? 6 * GRID_BLOCK_PX : 13 * GRID_BLOCK_PX,
    MENU_TEXTBOX_ROWSTYLES: DISPLAY_MODE_PORTRAIT ? [ BUBBLE_TOP, BUBBLE_MIDDLE ] : [ BUBBLE_TOP, BUBBLE_MIDDLE, BUBBLE_MIDDLE ]
}